-- Silkcrayon Studio OS V3 upgrade. Safe to run after the original schema.
alter table public.customers add column if not exists instagram text;
alter table public.customers add column if not exists date_of_birth date;
alter table public.customers add column if not exists area text;
alter table public.customers add column if not exists preferred_engineer text;
alter table public.customers add column if not exists preferred_genre text;
alter table public.customers add column if not exists goals text;
alter table public.customers add column if not exists admin_notes text;

alter table public.bookings add column if not exists harmful_music_policy_accepted boolean not null default false;
alter table public.bookings add column if not exists policy_accepted_at timestamptz;
alter table public.bookings add column if not exists assigned_engineer text;

create table if not exists public.session_reports (
 id uuid primary key default gen_random_uuid(),
 booking_id uuid references public.bookings(id) on delete set null,
 customer_id uuid references public.customers(id) on delete set null,
 engineer text not null,
 artist_name text not null,
 session_date date not null,
 start_time time,
 actual_hours numeric(6,2) not null check (actual_hours > 0),
 payment_method text,
 engineer_fee_pence integer not null default 0 check (engineer_fee_pence >= 0),
 studio_fee_pence integer not null default 0 check (studio_fee_pence >= 0),
 studio text not null default 'Cardiff Bay',
 work_completed text,
 files_status text,
 follow_up text,
 notes text,
 created_at timestamptz not null default now()
);
create index if not exists session_reports_date_idx on public.session_reports(session_date);
create index if not exists session_reports_customer_idx on public.session_reports(customer_id);
alter table public.session_reports enable row level security;

create table if not exists public.page_views (
 id bigint generated by default as identity primary key,
 path text not null,
 referrer text,
 visitor_id text,
 created_at timestamptz not null default now()
);
create index if not exists page_views_created_idx on public.page_views(created_at);
alter table public.page_views enable row level security;

-- Upgrade reservation RPC to record policy acceptance.
drop function if exists public.reserve_booking(uuid,text,text,date,time,time,integer,text,text,integer,timestamptz);
create or replace function public.reserve_booking(
  p_customer_id uuid, p_service_slug text, p_service_name text, p_booking_date date,
  p_start_time time, p_end_time time, p_duration_minutes integer, p_genre text,
  p_notes text, p_amount_pence integer, p_hold_expires_at timestamptz,
  p_harmful_music_policy_accepted boolean default false
) returns uuid language plpgsql security definer set search_path=public as $$
declare new_id uuid;
begin
  perform pg_advisory_xact_lock(hashtext(p_booking_date::text));
  if exists(select 1 from public.blockouts b where b.booking_date=p_booking_date and p_start_time<b.end_time and p_end_time>b.start_time) then raise exception 'slot_unavailable'; end if;
  if exists(select 1 from public.bookings b where b.booking_date=p_booking_date and b.status in ('pending','confirmed') and (b.status='confirmed' or b.hold_expires_at is null or b.hold_expires_at>now()) and p_start_time<b.end_time and p_end_time>b.start_time) then raise exception 'slot_unavailable'; end if;
  insert into public.bookings(customer_id,service_slug,service_name,booking_date,start_time,end_time,duration_minutes,genre,notes,amount_pence,status,payment_status,hold_expires_at,harmful_music_policy_accepted,policy_accepted_at)
  values(p_customer_id,p_service_slug,p_service_name,p_booking_date,p_start_time,p_end_time,p_duration_minutes,p_genre,p_notes,p_amount_pence,'pending','unpaid',p_hold_expires_at,p_harmful_music_policy_accepted,case when p_harmful_music_policy_accepted then now() else null end)
  returning id into new_id;
  return new_id;
end; $$;
revoke all on function public.reserve_booking(uuid,text,text,date,time,time,integer,text,text,integer,timestamptz,boolean) from public;
