import AdminNav from '../../../components/AdminNav';
import {requireOwner} from '../../../lib/auth';
import {getAdminDb} from '../../../lib/supabase';
import {formatGBP} from '../../../lib/services';
import AnalyticsTrend from '../../../components/AnalyticsTrend';
import Link from 'next/link';
export const dynamic='force-dynamic';
const pct=(a,b)=>b?Math.round(a/b*100):0;
export default async function Analytics({searchParams}){const ctx=await requireOwner(),sp=await searchParams,requested=Number(sp?.range||30),range=[7,30,90].includes(requested)?requested:30,db=getAdminDb(),now=new Date(),today=now.toISOString().slice(0,10),month=today.slice(0,7)+'-01',since90=new Date(Date.now()-90*864e5).toISOString().slice(0,10),viewsSince=new Date(Date.now()-range*864e5).toISOString();const [{data:bookings=[]},{data:customers=[]},{data:reports=[]},{data:views=[]},{data:payments=[]}]=await Promise.all([db.from('bookings').select('*,customers(id,full_name,artist_name,email,marketing_source)').gte('booking_date',since90),db.from('customers').select('id,created_at,marketing_source'),db.from('session_reports').select('*').gte('session_date',since90),db.from('page_views').select('visitor_id,path,referrer,created_at').gte('created_at',viewsSince),db.from('studio_payments').select('*').gte('created_at',new Date(Date.now()-90*864e5).toISOString())]);const monthBookings=bookings.filter(b=>b.booking_date>=month),paidMonth=monthBookings.filter(b=>b.payment_status==='paid'),revenue=paidMonth.filter(b=>b.payment_method!=='credits').reduce((s,b)=>s+b.amount_pence,0),hours=paidMonth.reduce((s,b)=>s+b.duration_minutes/60,0),customerCounts={};bookings.filter(b=>b.payment_status==='paid').forEach(b=>customerCounts[b.customer_id]=(customerCounts[b.customer_id]||0)+1);const paying=Object.keys(customerCounts).length,returning=Object.values(customerCounts).filter(n=>n>1).length;const unique=new Set(views.map(v=>v.visitor_id).filter(Boolean)).size,packages=payments.filter(p=>p.kind==='package'&&p.status==='paid'),packageRevenue=packages.reduce((s,p)=>s+p.amount_pence,0);const sources={};customers.forEach(c=>{const s=c.marketing_source||'Not recorded';sources[s]=(sources[s]||0)+1});const eng={};reports.forEach(r=>{const k=r.engineer||'Unknown';eng[k]??={hours:0,sessions:0,pay:0};eng[k].hours+=Number(r.actual_hours||0);eng[k].sessions++;eng[k].pay+=r.engineer_fee_pence||0});const topPaths={};views.forEach(v=>topPaths[v.path]=(topPaths[v.path]||0)+1);
 const londonParts=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
 const dailyMap={};for(let i=range-1;i>=0;i--){const d=new Date(Date.now()-i*864e5),key=londonParts(d);dailyMap[key]={date:key,label:new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short'}).format(d),views:0,ids:new Set()}}
 views.forEach(v=>{const key=londonParts(new Date(v.created_at));if(dailyMap[key]){dailyMap[key].views++;if(v.visitor_id)dailyMap[key].ids.add(v.visitor_id)}});
 const daily=Object.values(dailyMap).map(d=>({date:d.date,label:d.label,views:d.views,unique:d.ids.size}));
 const hourly=Array.from({length:24},(_,hour)=>({hour,count:0}));views.forEach(v=>{const h=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',hourCycle:'h23'}).format(new Date(v.created_at)));if(Number.isFinite(h))hourly[h].count++});
 return <main className="adminPage"><header className="adminHeader"><div><p className="eyebrow">Silkcrayon OS · V7</p><h1>Growth & analytics</h1><p className="muted">The numbers that tell you whether the studio is getting busier and customers are coming back.</p></div><AdminNav profile={ctx.profile}/></header><section className="osMetrics"><div><small>Revenue · month</small><b>{formatGBP(revenue)}</b></div><div><small>Paid hours · month</small><b>{hours}</b></div><div><small>Repeat rate · 90d</small><b>{pct(returning,paying)}%</b></div><div><small>Visitors · {range}d</small><b>{unique}</b></div><div><small>Package sales · 90d</small><b>{formatGBP(packageRevenue)}</b></div><div><small>Avg £ / paid hour</small><b>{formatGBP(hours?Math.round(revenue/hours):0)}</b></div></section><section className="analyticsRange"><span>Period</span>{[7,30,90].map(n=><Link key={n} className={range===n?'active':''} href={`/admin/analytics?range=${n}`}>{n} days</Link>)}</section><AnalyticsTrend daily={daily} hourly={hourly} range={range}/><section className="dashboardSplit"><div className="adminSection"><p className="eyebrow">Acquisition</p><h2>New artist sources</h2>{Object.entries(sources).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div className="analyticsRow" key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="adminSection"><p className="eyebrow">Website</p><h2>Most viewed pages · {range}d</h2>{Object.entries(topPaths).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div className="analyticsRow" key={k}><span>{k}</span><b>{v}</b></div>)}</div></section><section className="adminSection"><p className="eyebrow">Team</p><h2>Engineer delivery · 90 days</h2><div className="tableWrap"><table><thead><tr><th>Engineer</th><th>Sessions</th><th>Reported hours</th><th>Engineer pay</th></tr></thead><tbody>{Object.entries(eng).sort((a,b)=>b[1].hours-a[1].hours).map(([name,x])=><tr key={name}><td><b>{name}</b></td><td>{x.sessions}</td><td>{x.hours.toFixed(1)}</td><td>{formatGBP(x.pay)}</td></tr>)}</tbody></table></div></section></main>}
