import AdminNav from '../../../components/AdminNav';
import {requireOwner} from '../../../lib/auth';
import {getAdminDb} from '../../../lib/supabase';
export const dynamic='force-dynamic';
const prettyType=t=>({files_ready_email:'Files ready · email',files_ready_sms:'Files ready · SMS'}[t]||String(t||'').replaceAll('_',' '));
const when=v=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Europe/London'}):'—';
export default async function Automation(){
 const ctx=await requireOwner(),db=getAdminDb();
 const [{data:logs=[]},{data:deliveries=[]}]=await Promise.all([
  db.from('notification_log').select('*,customers(full_name,artist_name)').order('created_at',{ascending:false}).limit(150),
  db.from('session_deliveries').select('id,booking_id,delivery_type,file_name,created_at,expires_at,deleted_at,first_downloaded_at,last_downloaded_at,download_count,customers(full_name,artist_name)').order('created_at',{ascending:false}).limit(50)
 ]);
 const counts=logs.reduce((a,l)=>(a[l.status]=(a[l.status]||0)+1,a),{});
 return <main className="adminPage"><header className="adminHeader"><div><p className="eyebrow">Silkcrayon OS · V20.7.4</p><h1>Automations</h1><p className="muted">See what Silkcrayon sent, whether it succeeded, and whether delivered work has actually been opened.</p></div><AdminNav profile={ctx.profile}/></header><section className="profileMetrics"><div><small>Sent</small><b>{counts.sent||0}</b></div><div><small>Queued</small><b>{counts.queued||0}</b></div><div><small>Skipped</small><b>{counts.skipped||0}</b></div><div><small>Failed</small><b>{counts.failed||0}</b></div></section><section className="adminSection"><h2>Customer journey</h2><div className="automationJourney"><span><b>01</b> Booking confirmation</span><i>→</i><span><b>02</b> Engineer assigned</span><i>→</i><span><b>03</b> 24h reminder</span><i>→</i><span><b>04</b> Session</span><i>→</i><span><b>05</b> Files ready</span><i>→</i><span><b>06</b> Downloaded</span><i>→</i><span><b>07</b> Rebook</span></div></section><section className="adminSection"><h2>File delivery activity</h2><p className="muted">A delivery is only marked downloaded when the customer presses the download button — opening the email alone does not count.</p><div className="tableWrap"><table><thead><tr><th>Artist</th><th>Delivery</th><th>Sent</th><th>First download</th><th>Downloads</th><th>Last download</th></tr></thead><tbody>{deliveries.length?deliveries.map(d=><tr key={d.id}><td>{d.customers?.artist_name||d.customers?.full_name||'—'}</td><td>{d.delivery_type==='upload'?(d.file_name||'Uploaded file'):'External link'}</td><td>{when(d.created_at)}</td><td>{d.first_downloaded_at?<span className="autoStatus sent">{when(d.first_downloaded_at)}</span>:<span className="autoStatus queued">Not yet</span>}</td><td>{Number(d.download_count||0)}</td><td>{when(d.last_downloaded_at)}</td></tr>):<tr><td colSpan="6">No file deliveries yet.</td></tr>}</tbody></table></div></section><section className="adminSection"><h2>Automation status</h2><p className="muted">Files-ready email and SMS sends are now logged individually below. Failed sends stay visible so you can immediately see if one channel did not reach the customer.</p></section><section className="adminSection"><h2>Recent messages</h2><div className="tableWrap"><table><thead><tr><th>Artist</th><th>Type</th><th>Channel</th><th>Recipient</th><th>Status</th><th>Sent</th></tr></thead><tbody>{logs.length?logs.map(l=><tr key={l.id}><td>{l.customers?.artist_name||l.customers?.full_name||'—'}</td><td>{prettyType(l.notification_type)}</td><td>{l.channel||'email'}</td><td>{l.recipient}</td><td><span className={`autoStatus ${l.status}`}>{l.status}</span></td><td>{when(l.sent_at||l.created_at)}</td></tr>):<tr><td colSpan="6">No automation events yet.</td></tr>}</tbody></table></div></section></main>
}
