import Link from 'next/link';
import SiteHeader from '../../components/SiteHeader';
import Reveal from '../../components/Reveal';
export const metadata={title:'Contact Silkcrayon Studios Cardiff',description:'Contact Silkcrayon Studios in Cardiff Bay for recording, music production, mixing and studio enquiries.',alternates:{canonical:'https://silkcrayon.com/contact'}};
export default function Contact(){const address=process.env.STUDIO_ADDRESS||'Silkcrayon Studios · Cardiff Bay';return <main className="marketingSite contactPage"><SiteHeader/>
 <section className="contactHero contactHeroV2"><div className="container contactHeroGrid"><Reveal><div><p className="eyebrow">Contact · Cardiff Bay</p><h1>Tell us what<br/><span>you’re making.</span></h1><p className="lede">Ready to book? Choose a session online. Need production, mixing or something less straightforward? Send us the project and we’ll point you in the right direction.</p><div className="actions"><Link className="button primary" href="/booking">Book a session <span>↗</span></Link><Link className="textLink" href="/enquire">Make an enquiry →</Link></div></div></Reveal><Reveal delay={100}><div className="contactStudioImage"><img src="/images/doorway.webp" alt="Entrance to Silkcrayon Studios in Cardiff Bay"/><div><b>Silkcrayon Studios</b><span>{address}</span></div></div></Reveal></div></section>
 <section className="section contactRoutes"><div className="container"><Reveal><p className="eyebrow">Choose the quickest route</p></Reveal><div className="contactRouteGrid"><Reveal><Link href="/booking"><span>01</span><h2>Book studio time.</h2><p>See live availability and book vocal recording directly online.</p><b>Book now →</b></Link></Reveal><Reveal delay={70}><Link href="/enquire"><span>02</span><h2>Discuss a project.</h2><p>Production, mixing, podcasts or something bespoke — tell us what you need.</p><b>Make an enquiry →</b></Link></Reveal><Reveal delay={140}><a href="mailto:info@silkcrayon.com"><span>03</span><h2>Email the studio.</h2><p>For files, partnerships and anything that needs a proper conversation.</p><b>info@silkcrayon.com ↗</b></a></Reveal></div></div></section>
 <section className="section contactDetails"><div className="container contactDetailsGrid"><Reveal><div><p className="eyebrow">Find us</p><h2>Hidden in<br/>Cardiff Bay.</h2><p>The studio is inside Portland House, in the lane running through the building. Check the getting-here page before your first session for the exact entrance.</p><Link className="button outline" href="/getting-here">Getting here <span>↗</span></Link></div></Reveal><Reveal delay={90}><div className="contactLinkList"><a href="mailto:info@silkcrayon.com"><small>Email</small><b>info@silkcrayon.com</b><span>↗</span></a><a href="https://instagram.com/silkcrayon" target="_blank" rel="noreferrer"><small>Instagram</small><b>@silkcrayon</b><span>↗</span></a>{process.env.STUDIO_MAP_URL&&<a href={process.env.STUDIO_MAP_URL} target="_blank" rel="noreferrer"><small>Maps</small><b>Open directions</b><span>↗</span></a>}</div></Reveal></div></section>
 <section className="section finalCta"><div className="container"><Reveal><p className="eyebrow">Your next session</p><h2>Ready when you are.</h2><p>Live availability, secure payment and an engineer included.</p><Link className="button primary large" href="/booking">Book Silkcrayon <span>↗</span></Link></Reveal></div></section>
 <footer className="siteFooter"><div className="container footerGrid"><div><img src="/logo.png" alt="Silkcrayon"/><p>Cardiff Bay · Recording & creative development</p></div><div><Link href="/services">Services</Link><Link href="/recording-studio-cardiff">Recording Studio Cardiff</Link><Link href="/vocal-recording-cardiff">Vocal Recording</Link></div><div><Link href="/getting-here">Getting here</Link><Link href="/faq">FAQ</Link><a href="https://instagram.com/silkcrayon" target="_blank" rel="noreferrer">Instagram ↗</a></div></div></footer><Link href="/booking" className="mobileBookBar">Book a session <span>↗</span></Link>
 </main>}
