import Link from 'next/link';
import AdminNav from '../../components/AdminNav';
import { BookingStatus, BlockoutForm, EngineerAssign, ChangeRequestActions, PaymentReconcileButton, BookingPaymentAction, BookingOwnerActions, BlockoutList, CancellationRequestActions } from '../../components/AdminActions';
import { formatGBP } from '../../lib/services';
import { requireOwner } from '../../lib/auth';
import { getAdminDb } from '../../lib/supabase';
import {formatUkDate} from '../../lib/dates';
export const dynamic='force-dynamic';

function BookingCard({b,engineers}){return <article className="opsBookingCard"><div className="opsDate"><small>{formatUkDate(b.booking_date)}</small><b>{String(b.start_time).slice(0,5)}</b><span>{b.duration_minutes/60}h</span></div><div className="opsBookingMain"><div className="opsBookingTop"><div><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.service_name} · {formatGBP(b.amount_pence)} · <span className={b.payment_status==='paid'?'paidText':'dueText'}>{b.payment_status}</span></p></div><Link href={`/admin/customers/${b.customers?.id}`} className="textLink">Customer →</Link></div><>{b.preferred_engineer_name&&<div className="preferredEngineerFlag">★ Prefers {b.preferred_engineer_name}</div>}<EngineerAssign id={b.id} value={b.engineer_user_id} staff={engineers} preferredUserId={b.preferred_engineer_user_id} compact/></><BookingOwnerActions booking={b}/></div></article>}

export default async function Admin(){
 const ctx=await requireOwner();const db=getAdminDb();const now=new Date(),today=now.toISOString().slice(0,10),month=today.slice(0,7)+'-01';
 const monthDate=new Date(`${month}T00:00:00Z`),nextMonthDate=new Date(Date.UTC(monthDate.getUTCFullYear(),monthDate.getUTCMonth()+1,1)),prevMonthDate=new Date(Date.UTC(monthDate.getUTCFullYear(),monthDate.getUTCMonth()-1,1));
 const nextMonth=nextMonthDate.toISOString().slice(0,10),prevMonth=prevMonthDate.toISOString().slice(0,10); 
 const [{data:bookings=[]},{count:customers=0},{data:reports=[]},{data:views=[]},{data:engineers=[]},{data:blockouts=[]},{data:monthRevenueBookings=[]},{data:prevRevenueBookings=[]},{data:monthPayments=[]},{data:prevPayments=[]}]=await Promise.all([
  db.from('bookings').select('*,customers(id,full_name,email,artist_name,phone)').gte('booking_date',month).order('booking_date').order('start_time'),
  db.from('customers').select('*',{count:'exact',head:true}),
  db.from('session_reports').select('*').gte('session_date',month).lt('session_date',nextMonth),
  db.from('page_views').select('visitor_id,created_at').gte('created_at',month+'T00:00:00Z').lt('created_at',nextMonth+'T00:00:00Z'),
  db.from('staff_profiles').select('user_id,full_name,engineer_name,role,active').in('role',['engineer','owner']).eq('active',true).order('full_name'),
  db.from('blockouts').select('*').gte('booking_date',today).order('booking_date').order('start_time'),
  db.from('bookings').select('amount_pence,refunded_amount_pence,payment_status,payment_method,created_at,duration_minutes').in('payment_status',['paid','part_refunded','refunded']).neq('payment_method','credits').gte('created_at',month+'T00:00:00Z').lt('created_at',nextMonth+'T00:00:00Z'),
  db.from('bookings').select('amount_pence,refunded_amount_pence,payment_status,payment_method,created_at,duration_minutes').in('payment_status',['paid','part_refunded','refunded']).neq('payment_method','credits').gte('created_at',prevMonth+'T00:00:00Z').lt('created_at',month+'T00:00:00Z'),
  db.from('studio_payments').select('amount_pence,refunded_amount_pence,status,paid_at,created_at,session_hours,payment_category,kind').in('status',['paid','part_refunded','refunded']).gte('paid_at',month+'T00:00:00Z').lt('paid_at',nextMonth+'T00:00:00Z'),
  db.from('studio_payments').select('amount_pence,refunded_amount_pence,status,paid_at,created_at,session_hours,payment_category,kind').in('status',['paid','part_refunded','refunded']).gte('paid_at',prevMonth+'T00:00:00Z').lt('paid_at',month+'T00:00:00Z')
 ]);
 const netOfRefunds=x=>Math.max(0,Number(x.amount_pence||0)-Number(x.refunded_amount_pence||0));
 const bookingRevenue=monthRevenueBookings.reduce((s,b)=>s+netOfRefunds(b),0),paymentRevenue=monthPayments.reduce((s,p)=>s+netOfRefunds(p),0),paid=bookingRevenue+paymentRevenue;
 const previousRevenue=prevRevenueBookings.reduce((s,b)=>s+netOfRefunds(b),0)+prevPayments.reduce((s,p)=>s+netOfRefunds(p),0),revenueChange=previousRevenue?((paid-previousRevenue)/previousRevenue)*100:null;
 const extraRevenue=monthPayments.filter(p=>p.payment_category==='extra_time').reduce((s,p)=>s+netOfRefunds(p),0),otherStudioRevenue=paymentRevenue-extraRevenue;
 const upcoming=bookings.filter(b=>b.booking_date>=today&&!['cancelled','completed'].includes(b.status)),unassigned=upcoming.filter(b=>!b.engineer_user_id),cancelRequests=upcoming.filter(b=>b.cancellation_requested_at),changeRequests=upcoming.filter(b=>b.change_request_status==='pending');
 const outstanding=upcoming.filter(b=>!['paid','part_refunded','refunded'].includes(b.payment_status)&&b.payment_method!=='credits').reduce((s,b)=>s+Number(b.amount_pence||0),0),scheduledValue=upcoming.reduce((s,b)=>s+Number(b.amount_pence||0),0);
 const hours=monthRevenueBookings.filter(b=>b.payment_status==='paid').reduce((s,b)=>s+Number(b.duration_minutes||0)/60,0)+monthPayments.reduce((s,p)=>s+Number(p.session_hours||0),0),unique=new Set(views.map(v=>v.visitor_id).filter(Boolean)).size,engPay=reports.reduce((s,r)=>s+r.engineer_fee_pence,0),completedHours=reports.reduce((s,r)=>s+Number(r.actual_hours||0),0);
 return <main className="adminPage"><header className="adminHeader"><div><p className="eyebrow">Silkcrayon OS · V8</p><h1>Studio overview</h1><p className="muted">The studio at a glance — with anything needing your attention first.</p></div><AdminNav profile={ctx.profile}/></header>
 <section className="adminSection revenueDashboard"><div className="adminSectionHead"><div><p className="eyebrow">Revenue dashboard</p><h2>Money in · this month</h2><p className="muted">Collected revenue is based on when money was actually paid, net of refunds and excluding voided corrections.</p></div><Link className="button outline" href="/admin/accounting">Open accounting →</Link></div><div className="revenueHeroGrid"><div className="revenueHero"><small>Collected this month</small><b>{formatGBP(paid)}</b><span className={revenueChange===null?'muted':revenueChange>=0?'paidText':'dueText'}>{revenueChange===null?'No previous-month baseline':`${revenueChange>=0?'↑':'↓'} ${Math.abs(revenueChange).toFixed(0)}% vs last month`}</span></div><div className="revenueStat"><small>Last month</small><b>{formatGBP(previousRevenue)}</b></div><div className="revenueStat"><small>Upcoming value</small><b>{formatGBP(scheduledValue)}</b></div><div className="revenueStat"><small>Still to collect</small><b>{formatGBP(outstanding)}</b></div></div><div className="revenueBreakdown"><div><span>Session bookings</span><b>{formatGBP(bookingRevenue)}</b></div><div><span>Extra studio time</span><b>{formatGBP(extraRevenue)}</b></div><div><span>Other studio payments</span><b>{formatGBP(otherStudioRevenue)}</b></div></div></section>
 <section className="adminSection reconciliationBar"><div><p className="eyebrow">Payments</p><h2>Stripe reconciliation</h2><p className="muted">If an older Apple Pay/card booking shows unpaid, sync it against Stripe here.</p></div><PaymentReconcileButton/></section><section className="osMetrics"><div><small>Paid hours · month</small><b>{hours}</b></div><div><small>Needs assigning</small><b>{unassigned.length}</b></div><div><small>Upcoming</small><b>{upcoming.length}</b></div><div><small>Customers</small><b>{customers}</b></div><div><small>Visitors · month</small><b>{unique}</b></div></section>
 <section className={`adminSection attentionSection ${changeRequests.length?'hasAttention':''}`}><div className="adminSectionHead"><div><p className="eyebrow">Customer requests</p><h2>Session change requests</h2><p className="muted">Nothing moves until you confirm it. The assigned engineer has already been notified.</p></div><span className="attentionCount">{changeRequests.length}</span></div>{changeRequests.length?<div className="opsBookingList">{changeRequests.map(b=><article className="opsBookingCard changeRequestCard" key={b.id}><div className="opsDate"><small>CURRENT</small><b>{String(b.start_time).slice(0,5)}</b><span>{formatUkDate(b.booking_date)}</span></div><div className="opsBookingMain"><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.service_name}</p><div className="requestedSlot"><small>REQUESTED</small><b>{formatUkDate(b.change_requested_date)} · {String(b.change_requested_start).slice(0,5)}–{String(b.change_requested_end).slice(0,5)}</b></div>{b.change_request_note&&<p className="muted">“{b.change_request_note}”</p>}<ChangeRequestActions id={b.id}/></div></article>)}</div>:<div className="allClear">✓ No session change requests.</div>}</section>
 <section className={`adminSection attentionSection ${cancelRequests.length?'hasAttention':''}`}><div className="adminSectionHead"><div><p className="eyebrow">Customer requests</p><h2>Cancellation requests</h2><p className="muted">Review these before changing/refunding anything.</p></div><span className="attentionCount">{cancelRequests.length}</span></div>{cancelRequests.length?<div className="opsBookingList">{cancelRequests.map(b=><article className="opsBookingCard" key={b.id}><div className="opsDate"><small>{formatUkDate(b.booking_date)}</small><b>{String(b.start_time).slice(0,5)}</b></div><div className="opsBookingMain"><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.cancellation_request_note||'No note provided.'}</p><small>{b.payment_method==='credits'?'Booked with studio hours':'Card payment'} · {formatGBP(b.amount_pence)}</small><CancellationRequestActions booking={b}/></div></article>)}</div>:<div className="allClear">✓ No cancellation requests.</div>}</section><section className={`adminSection attentionSection ${unassigned.length?'hasAttention':''}`}><div className="adminSectionHead"><div><p className="eyebrow">Action required</p><h2>Needs assigning</h2><p className="muted">Any upcoming booking without an engineer. If it is still unassigned when the reminder runs, Studio OS will assign the default owner/engineer before contacting the customer.</p></div><span className="attentionCount">{unassigned.length}</span></div>{unassigned.length?<div className="opsBookingList">{unassigned.map(b=><BookingCard key={b.id} b={b} engineers={engineers}/>)}</div>:<div className="allClear">✓ Everything is assigned.</div>}</section>
 <section className="adminSection"><div className="adminSectionHead"><div><p className="eyebrow">Schedule</p><h2>Upcoming sessions</h2><p className="muted">Every upcoming session, including anything still unassigned.</p></div><div className="adminHeadActions"><Link className="button outline" href="/admin/calendar">Calendar →</Link><Link className="button outline" href="/admin/bookings/new">+ New booking</Link><Link className="button outline" href="/admin/sessions">Session reports →</Link></div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Time</th><th>Artist</th><th>Engineer</th><th>Value</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>{upcoming.length?upcoming.map(b=><tr key={b.id} className={!b.engineer_user_id?'unassignedRow':''}><td>{formatUkDate(b.booking_date)}</td><td>{String(b.start_time).slice(0,5)}–{String(b.end_time).slice(0,5)}</td><td><Link className="customerLink" href={`/admin/customers/${b.customers?.id}`}><b>{b.customers?.artist_name||b.customers?.full_name}</b></Link><small>{b.service_name}</small></td><td>{!b.engineer_user_id&&<span className="unassignedBadge">UNASSIGNED</span>}<EngineerAssign id={b.id} value={b.engineer_user_id} staff={engineers}/></td><td>{formatGBP(b.amount_pence)}</td><td><BookingPaymentAction booking={b} compact/></td><td><BookingStatus id={b.id} status={b.status}/></td><td><Link className="textLink" href={`/admin/engineer/session/${b.id}`}>View session →</Link></td></tr>):<tr><td colSpan="8">No upcoming bookings.</td></tr>}</tbody></table></div></section>
 <section className="dashboardSplit"><div className="adminSection"><p className="eyebrow">Operations</p><h2>Engineer reporting</h2><div className="bigStat">{completedHours}<small>reported hours this month</small></div><p className="muted">Engineer pay logged: {formatGBP(engPay)}</p><Link className="textLink" href="/admin/sessions">Open session reports →</Link></div><div className="adminSection"><p className="eyebrow">Availability</p><h2>Block studio time</h2><BlockoutForm/><div className="blockedTimes"><h3>Blocked time</h3><BlockoutList items={blockouts}/></div></div></section></main>
}
