import Link from 'next/link';
import AdminNav from '../../components/AdminNav';
import { BookingStatus, BlockoutForm, EngineerAssign } from '../../components/AdminActions';
import { formatGBP } from '../../lib/services';
import { requireOwner } from '../../lib/auth';
import { getAdminDb } from '../../lib/supabase';
export const dynamic='force-dynamic';

function BookingCard({b,engineers}){return <article className="opsBookingCard"><div className="opsDate"><small>{b.booking_date}</small><b>{String(b.start_time).slice(0,5)}</b><span>{b.duration_minutes/60}h</span></div><div className="opsBookingMain"><div className="opsBookingTop"><div><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.service_name} · {formatGBP(b.amount_pence)} · <span className={b.payment_status==='paid'?'paidText':'dueText'}>{b.payment_status}</span></p></div><Link href={`/admin/customers/${b.customers?.id}`} className="textLink">Customer →</Link></div><EngineerAssign id={b.id} value={b.engineer_user_id} staff={engineers} compact/></div></article>}

export default async function Admin(){
 const ctx=await requireOwner();const db=getAdminDb();const today=new Date().toISOString().slice(0,10),month=today.slice(0,7)+'-01';
 const [{data:bookings=[]},{count:customers=0},{data:reports=[]},{data:views=[]},{data:engineers=[]}]=await Promise.all([
  db.from('bookings').select('*,customers(id,full_name,email,artist_name,phone)').gte('booking_date',month).order('booking_date').order('start_time'),
  db.from('customers').select('*',{count:'exact',head:true}),
  db.from('session_reports').select('*').gte('session_date',month),
  db.from('page_views').select('visitor_id,created_at').gte('created_at',month+'T00:00:00Z'),
  db.from('staff_profiles').select('user_id,full_name,engineer_name,role,active').eq('role','engineer').eq('active',true).order('full_name')
 ]);
 const paid=bookings.filter(b=>b.payment_status==='paid').reduce((s,b)=>s+b.amount_pence,0),upcoming=bookings.filter(b=>b.booking_date>=today&&!['cancelled','completed'].includes(b.status)),unassigned=upcoming.filter(b=>!b.engineer_user_id&&b.payment_status==='paid'),assigned=upcoming.filter(b=>b.engineer_user_id),hours=bookings.filter(b=>b.payment_status==='paid').reduce((s,b)=>s+b.duration_minutes/60,0),unique=new Set(views.map(v=>v.visitor_id).filter(Boolean)).size,engPay=reports.reduce((s,r)=>s+r.engineer_fee_pence,0),completedHours=reports.reduce((s,r)=>s+Number(r.actual_hours||0),0);
 return <main className="adminPage"><header className="adminHeader"><div><p className="eyebrow">Silkcrayon OS · V8</p><h1>Studio overview</h1><p className="muted">The studio at a glance — with anything needing your attention first.</p></div><AdminNav profile={ctx.profile}/></header>
 <section className="osMetrics"><div><small>Revenue · month</small><b>{formatGBP(paid)}</b></div><div><small>Paid hours · month</small><b>{hours}</b></div><div><small>Needs assigning</small><b>{unassigned.length}</b></div><div><small>Upcoming</small><b>{upcoming.length}</b></div><div><small>Customers</small><b>{customers}</b></div><div><small>Visitors · month</small><b>{unique}</b></div></section>
 <section className={`adminSection attentionSection ${unassigned.length?'hasAttention':''}`}><div className="adminSectionHead"><div><p className="eyebrow">Action required</p><h2>Needs assigning</h2><p className="muted">Paid bookings that don’t yet have an engineer.</p></div><span className="attentionCount">{unassigned.length}</span></div>{unassigned.length?<div className="opsBookingList">{unassigned.map(b=><BookingCard key={b.id} b={b} engineers={engineers}/>)}</div>:<div className="allClear">✓ Everything is assigned.</div>}</section>
 <section className="adminSection"><div className="adminSectionHead"><div><p className="eyebrow">Schedule</p><h2>Upcoming sessions</h2><p className="muted">Assigned sessions coming up next.</p></div><Link className="button outline" href="/admin/sessions">Session reports →</Link></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Time</th><th>Artist</th><th>Engineer</th><th>Value</th><th>Status</th></tr></thead><tbody>{assigned.length?assigned.map(b=><tr key={b.id}><td>{b.booking_date}</td><td>{String(b.start_time).slice(0,5)}–{String(b.end_time).slice(0,5)}</td><td><Link className="customerLink" href={`/admin/customers/${b.customers?.id}`}><b>{b.customers?.artist_name||b.customers?.full_name}</b></Link><small>{b.service_name}</small></td><td><EngineerAssign id={b.id} value={b.engineer_user_id} staff={engineers}/></td><td>{formatGBP(b.amount_pence)}</td><td><BookingStatus id={b.id} status={b.status}/></td></tr>):<tr><td colSpan="6">No assigned upcoming bookings.</td></tr>}</tbody></table></div></section>
 <section className="dashboardSplit"><div className="adminSection"><p className="eyebrow">Operations</p><h2>Engineer reporting</h2><div className="bigStat">{completedHours}<small>reported hours this month</small></div><p className="muted">Engineer pay logged: {formatGBP(engPay)}</p><Link className="textLink" href="/admin/sessions">Open session reports →</Link></div><div className="adminSection"><p className="eyebrow">Availability</p><h2>Block studio time</h2><BlockoutForm/></div></section></main>
}
