import assert from 'node:assert/strict';
import {verifiedPurchase, GOOGLE_ADS_PURCHASE_DESTINATION} from '../lib/googleAds.js';
import {reportPurchase} from '../lib/reportGoogleAdsPurchase.js';
const session={id:'cs_live_abc',payment_intent:'pi_abc',mode:'payment',status:'complete',payment_status:'paid',livemode:true,currency:'gbp',amount_total:12345,metadata:{booking_id:'booking'}};
const booking={stripe_checkout_session_id:session.id,stripe_payment_intent_id:'pi_abc',payment_status:'paid',status:'confirmed'};
const db=record=>({from(){return {select(){return this},eq(){return this},async maybeSingle(){return {data:record}}}}});
const purchase=await verifiedPurchase(session,db(booking));
assert.deepEqual(purchase,{transaction_id:'pi_abc',value:123.45,currency:'GBP'});
for(const patch of [{payment_status:'unpaid'},{status:'open'},{livemode:false},{currency:'usd'},{amount_total:0},{amount_total:null},{amount_total:NaN},{payment_intent:null}])assert.equal(await verifiedPurchase({...session,...patch},db(booking)),null);
for(const patch of [{payment_status:'unpaid'},{status:'cancelled'},{stripe_checkout_session_id:'cs_live_other'},{stripe_payment_intent_id:'pi_other'}])assert.equal(await verifiedPurchase(session,db({...booking,...patch})),null);
assert.equal(await verifiedPurchase(session,db(null)),null);
for(const [metadata,record] of [[{studio_payment_id:'payment'},{...booking,status:'paid'}],[{mix_job_id:'mix'},{...booking,paid_at:'2026-09-15',paid_amount_pence:12345}]])assert.deepEqual(await verifiedPurchase({...session,metadata},db(record)),purchase);
let calls=[];const memory=new Map();const storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)};
const win={localStorage:storage,sessionStorage:storage,gtag:(...args)=>calls.push(args)};
const opts={win,hasConsent:()=>true};
assert.equal(await reportPurchase(purchase,{...opts,hasConsent:()=>false}),false);
assert.equal(await reportPurchase(purchase,{...opts,isCancelled:()=>true}),false);
assert.equal(calls.length,0);
await Promise.all([reportPurchase(purchase,opts),reportPurchase(purchase,opts)]);
assert.equal(calls.length,1);
assert.equal(calls[0][2].send_to,GOOGLE_ADS_PURCHASE_DESTINATION);
assert.equal(calls[0][2].value,123.45);
const second={...purchase,transaction_id:'pi_second'};
assert.equal(await reportPurchase(second,{...opts,win:{...win,gtag:undefined}}),false);
await reportPurchase(second,opts);assert.equal(calls.length,2);
const broken={gtag:win.gtag,get localStorage(){throw Error('blocked')},get sessionStorage(){throw Error('blocked')}};
await reportPurchase({...purchase,transaction_id:'pi_blocked'},{...opts,win:broken});assert.equal(calls.length,3);
assert.equal(await reportPurchase({...purchase,transaction_id:'pi_throw'},{...opts,win:{gtag:()=>{throw Error('tag')}}}),false);
await reportPurchase({...purchase,transaction_id:'pi_throw'},opts);assert.equal(calls.length,4);
// Reload a fresh module: persistent storage still blocks the previous payment.
const fresh=await import('../lib/reportGoogleAdsPurchase.js?reload');
await fresh.reportPurchase(purchase,opts);assert.equal(calls.length,4);
console.log('Google Ads verification and duplicate reporting tests passed');
