import assert from 'node:assert/strict';
import fs from 'node:fs';
import {issueFormToken,validFormToken} from '../lib/formToken.js';
import {looksLikeObviousSpam} from '../lib/leadSpam.js';
process.env.FORM_SECURITY_SECRET='local-test-secret';
const now=Date.now();const token=issueFormToken(now-2000);
assert(validFormToken(token,now));
for(const bad of ['',token+'x',issueFormToken(now),issueFormToken(now+5000),issueFormToken(now-7200001),token.replace(/^./,'0')])assert(!validFormToken(bad,now));
const source=fs.readFileSync(new URL('../lib/publicFormGuard.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
let calls=[];let permit=true;let unavailable=false;const seen=new Set();
const rateLimit=async(req,opts)=>{calls.push(opts);if(unavailable)throw Error('offline');if(!permit)return false;if(opts.scope==='public-form-token'){if(seen.has(opts.identity))return false;seen.add(opts.identity)}return true};
const NextResponse={json:(body,{status=200}={})=>({body,status})};
const fn=new Function('NextResponse','validFormToken','rateLimit','looksLikeObviousSpam',source.replace('export async function','async function')+';return publicFormGuard');
const guard=fn(NextResponse,validFormToken,rateLimit,looksLikeObviousSpam);
const req={url:'https://silkcrayon.com/api/artist-support',headers:new Headers({origin:'https://silkcrayon.com'})};
const fresh=()=>({form_token:issueFormToken(Date.now()-2000),email:'artist@example.com',fullName:'Nathan Misra',goals:'I want to release my first single',blockers:'I need help planning the release'});
const good=fresh();assert.equal(await guard(req,good,{lead:true}),null);assert.equal((await guard(req,good)).status,409);
assert(calls.some(x=>x.scope==='public-form-ip'&&!x.identity));assert(calls.some(x=>x.scope==='public-form-email'&&x.identityOnly));
for(const patch of [{website:'spam'},{form_token:''},{email:'bad'},{goals:'x'.repeat(6001)}])assert.equal((await guard(req,{...fresh(),...patch})).status,400);
const spam={...fresh(),fullName:'KQDNyJTSbvqnMhOxaDv',artistName:'Jbaumgfq',email:'ja.c.o.ru.f74.5@gmail.com',goals:'nYOWeWeabUeBWjimQjPFvUf'};assert.equal((await guard(req,spam,{lead:true})).status,400);
assert.equal((await guard({...req,headers:new Headers({origin:'https://spam.example'})},fresh())).status,403);
permit=false;assert.equal((await guard(req,fresh())).status,429);permit=true;
unavailable=true;assert.equal((await guard(req,fresh())).status,503);
for(const route of ['enquiries','artist-support','mix-requests','checkout','store/checkout','marketing/signup','customer/access'])assert(fs.readFileSync(new URL(`../app/api/${route}/route.js`,import.meta.url),'utf8').includes('await publicFormGuard('));
console.log('Public form security tests passed: legitimate submissions, screenshot spam, forged/expired tokens, replay, cross-site, limits and outage.');
