import SeoServicePage from "../../components/SeoServicePage";
export const metadata={title:"Mixing & Mastering Cardiff | Mix & Master Online | Silkcrayon",description:"Professional mixing and mastering from Silkcrayon Studios Cardiff. Vocal cleanup, balance, EQ, compression, effects, automation, mastering, private review and focused revisions.",alternates:{canonical:"https://silkcrayon.com/mixing-mastering-cardiff"},openGraph:{title:"Mixing & Mastering Cardiff | Silkcrayon Studios",description:"Professional mix and master service with a clear review process, focused revisions and release-ready finishing from Silkcrayon Studios Cardiff.",url:"https://silkcrayon.com/mixing-mastering-cardiff",type:"website"}};
export default function Page(){return <SeoServicePage
 serviceName="Mixing and mastering" serviceDescription="Professional mixing and mastering for artists in Cardiff and beyond, including vocal cleanup, balance, processing, effects, automation, mastering and private client review." canonicalPath="/mixing-mastering-cardiff"
 eyebrow="Mixing & mastering · Cardiff" title="Finish the record" accent="properly."
 intro="A mix should make the intention of the song clearer — not flatten it into a preset. We shape the vocal, production and low end, then master the finished record for a confident release-ready result."
 proof={["Mix & Master available","Private review link","Focused revisions","Remote or Cardiff"]}
 points={[{title:"A mix built around the song",copy:"We work through balance, EQ, compression, vocal cleanup, effects and automation to make the record feel deliberate while keeping its identity intact."},{title:"A review process that stays focused",copy:"You receive a private review link with Approve Mix as the main action. If something genuinely needs changing, included revision rounds keep feedback specific and useful."},{title:"Mastering that finishes the job",copy:"For Mix & Master projects, the approved mix receives a final mastering pass for overall tone, level and translation across headphones, cars, speakers and streaming playback."}]}
 storyTitle="From session files to a record you can release."
 story={["Send the strongest source files you have, along with references and context for what you want the record to feel like. We organise the material, clean up what distracts and make the mix decisions that help the song communicate.","You do not need to sit beside the engineer for the whole process. Mixes can be handled remotely through Silkcrayon's private delivery and review system, while Cardiff artists can keep recording and finishing work connected to the same studio."]}
 storyImage="/images/workstation.webp" storyImageAlt="Mixing and mastering workstation at Silkcrayon Studios Cardiff"
 process={[{title:"Send the track",copy:"Upload your source files and tell us the direction, references and anything we need to understand before starting."},{title:"We build the mix",copy:"Vocals and production are cleaned, balanced and shaped with EQ, compression, effects, automation and detailed mix decisions."},{title:"Review privately",copy:"Your mix arrives through a private review page. Approve it when it feels right, or send one focused revision request with timestamps where useful."},{title:"Master & deliver",copy:"Once the mix is approved, Mix & Master projects receive the final mastering pass and release-ready files are delivered securely."}]}
 faqs={[{q:"What is included in Mix & Master?",a:"Mixing covers the detailed balance and processing of the individual elements of your song, including vocal cleanup, EQ, compression, effects and automation where needed. Mastering is the final pass on the finished stereo mix for overall tone, level and translation."},{q:"Can I send a track remotely?",a:"Yes. You can submit your track and source files online, receive your mix through a private review link and approve or request a focused revision without coming to the studio."},{q:"How do revisions work?",a:"Your quote states the number of included revision rounds. The review page is designed around approving the mix first; if a specific change is genuinely needed, you can send focused notes and timestamps."},{q:"How long does mixing and mastering take?",a:"Turnaround is agreed when the project is set up and begins once payment and the complete source files are received. Your confirmation email states the turnaround for your specific project."},{q:"Do I need separate mastering if I book Mix & Master?",a:"No. If your service is set up as Mix & Master, mastering is already included after the mix is approved."}]}
 ctaHref="/mix-request" cta="Upload a track for a quote" image="/images/wide.webp" imageAlt="Professional mixing and mastering studio in Cardiff"
 related={[{kicker:"Record first",title:"Vocal recording Cardiff",copy:"Capture the performance properly →",href:"/vocal-recording-cardiff"},{kicker:"The studio",title:"Recording Studio Cardiff",copy:"Explore Silkcrayon Studios →",href:"/recording-studio-cardiff"},{kicker:"Build the record",title:"Music production Cardiff",copy:"Develop the song →",href:"/music-production-cardiff"}]}
 />}
