import PageTracker from "../components/PageTracker";
import PwaRegister from "../components/PwaRegister";
import GoogleConsent from "../components/GoogleConsent";
import Script from "next/script";
import "./globals.css";
const siteUrl="https://silkcrayon.com";
const googleAdsId=process.env.NEXT_PUBLIC_GOOGLE_ADS_ID||"AW-18437935262";
export const viewport={width:"device-width",initialScale:1,viewportFit:"cover",themeColor:"#050505"};
export const metadata={metadataBase:new URL(siteUrl),title:{default:"Recording Studio Cardiff | Silkcrayon Studios",template:"%s | Silkcrayon Studios"},description:"Premium vocal recording, mixing and release-ready music production in a hidden 1926 bank vault in Cardiff Bay.",applicationName:"Silkcrayon Studios",manifest:"/manifest.webmanifest",alternates:{canonical:"/"},openGraph:{type:"website",locale:"en_GB",url:siteUrl,siteName:"Silkcrayon Studios",title:"Recording Studio Cardiff | Silkcrayon Studios",description:"Expert vocal recording and release-ready production in Cardiff Bay.",images:[{url:"/images/wide.webp",width:1600,height:1067,alt:"Silkcrayon Studios in Cardiff Bay"}]},twitter:{card:"summary_large_image",title:"Silkcrayon Studios — Cardiff",description:"Expert vocal recording and release-ready production in Cardiff Bay.",images:["/images/wide.webp"]},verification:{google:process.env.GOOGLE_SITE_VERIFICATION||undefined},appleWebApp:{capable:true,title:"Silkcrayon OS",statusBarStyle:"black-translucent"},icons:{apple:"/icons/apple-touch-icon.png"}};
export default function RootLayout({children}){return <html lang="en-GB"><head><Script id="google-consent-mode" strategy="beforeInteractive">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=window.gtag||gtag;gtag('consent','default',{ad_storage:'denied',analytics_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});`}</Script><Script id="google-ads-tag" strategy="afterInteractive" src={`https://www.googletagmanager.com/gtag/js?id=${googleAdsId}`}/><Script id="google-ads-config" strategy="afterInteractive">{`window.gtag&&window.gtag('js',new Date());window.gtag&&window.gtag('config','${googleAdsId}');`}</Script></head><body><PwaRegister/><GoogleConsent/><PageTracker/>{children}</body></html>}
