import SeoServicePage from "../../components/SeoServicePage";
export const metadata={title:"Music Production Cardiff | Artist Development | Silkcrayon",description:"Bespoke music production in Cardiff for artists who want to develop songs, arrangements and a distinctive sound. Production, recording and creative direction at Silkcrayon Studios.",alternates:{canonical:"https://silkcrayon.com/music-production-cardiff"},openGraph:{title:"Music Production Cardiff | Silkcrayon Studios",description:"Bespoke music production and artist development in Cardiff Bay — from early idea and arrangement through recording and final direction.",url:"https://silkcrayon.com/music-production-cardiff",type:"website"}};
export default function Page(){return <SeoServicePage
 eyebrow="Music production · Cardiff"
 title="Build the record"
 accent="around the artist."
 intro="Production is not filling a template with sounds. We develop the song around your voice, taste and direction — from an early idea or demo through arrangement, recording and a coherent finished record."
 proof={["Bespoke production","Artist development","Vocal recording","Project based"]}
 points={[{title:"Start where the idea is",copy:"Bring a voice note, reference, demo, beat or half-built session. We identify what is already working and what the song actually needs next."},{title:"Shape the arrangement",copy:"Structure, dynamics, musical choices and transitions are developed around the emotional direction of the record rather than a generic formula."},{title:"One creative ecosystem",copy:"Production, vocal recording and finishing can happen within the same studio relationship, keeping the intent intact from first idea to final decisions."}]}
 storyTitle="The goal is a sound that belongs to you."
 story={["The best production process does not erase the artist under a producer's signature. It gives the artist's strongest ideas a clearer shape.","That might mean building an instrumental from the ground up, developing an existing beat, restructuring a song, finding the right vocal approach or simply knowing what to remove. The process is tailored to the project rather than sold as a fixed hourly product."]}
 storyImage="/images/wide2.webp" storyImageAlt="Music production and artist development at Silkcrayon Studios Cardiff"
 process={[{title:"Send the idea",copy:"Tell us what you are making and share any demos, references or existing sessions that help explain the direction."},{title:"Find the route",copy:"We work out whether the record needs full production, arrangement, recording, development or a combination."},{title:"Build together",copy:"Develop the musical and vocal choices around the artist instead of forcing the song through a preset workflow."},{title:"Take it to finish",copy:"Move into recording, mixing and final decisions while preserving the creative intent established at the start."}]}
 ctaHref="/enquire?type=production" cta="Enquire about production" image="/images/wide2.webp" imageAlt="Music production studio in Cardiff at Silkcrayon Studios"
 related={[{kicker:"Record the performance",title:"Premium vocal recording",copy:"Vocal sessions in Cardiff →",href:"/vocal-recording-cardiff"},{kicker:"The space",title:"Recording Studio Cardiff",copy:"Explore Silkcrayon Studios →",href:"/recording-studio-cardiff"},{kicker:"Finish the record",title:"Mixing & mastering",copy:"Explore finishing support →",href:"/mixing-mastering-cardiff"}]}
 />}
