"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';

function when(value){if(!value)return 'Not synced yet';return `Last synced ${new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}`}
export default function AppleCalendarConnections({sources=[]}){
 const router=useRouter(),[open,setOpen]=useState(false),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 async function request(url,options){const r=await fetch(url,options),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Something went wrong.');return j}
 async function add(e){e.preventDefault();setBusy('add');setMsg('Checking and connecting…');const body=Object.fromEntries(new FormData(e.currentTarget).entries());body.blockAllDay=body.blockAllDay==='on';try{const j=await request('/api/admin/calendar-connections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setMsg(j.warning||`Connected · ${j.count||0} busy times synced ✓`);e.currentTarget.reset();setOpen(false);router.refresh()}catch(e){setMsg(e.message)}finally{setBusy('')}}
 async function patch(id,body){setBusy(id);setMsg('Saving…');try{const j=await request(`/api/admin/calendar-connections/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setMsg(`Saved · ${j.count||0} busy times synced ✓`);router.refresh()}catch(e){setMsg(e.message)}finally{setBusy('')}}
 async function sync(id=''){setBusy(id||'all');setMsg('Syncing Apple Calendar…');try{const j=await request('/api/admin/calendar-connections/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(id?{id}:{})});const failed=j.results?.filter(x=>x.error).length||0;setMsg(failed?`${failed} calendar${failed===1?'':'s'} could not sync. Check below.`:'Calendars synced ✓');router.refresh()}catch(e){setMsg(e.message)}finally{setBusy('')}}
 async function remove(id,name){if(!confirm(`Disconnect ${name}? Its imported busy times will be removed.`))return;setBusy(id);try{await request(`/api/admin/calendar-connections/${id}`,{method:'DELETE'});setMsg('Calendar disconnected.');router.refresh()}catch(e){setMsg(e.message)}finally{setBusy('')}}
 return <div className="appleConnections">
  <div className="appleConnectionsHead"><div><h3>Calendars that block bookings</h3><p className="muted">Connect each Apple calendar you want the studio to respect. Event names stay private.</p></div><div className="appleConnectionButtons"><button className="miniButton solid" onClick={()=>setOpen(v=>!v)}>{open?'Close':'+ Connect calendar'}</button>{sources.length>0&&<button className="miniButton" disabled={!!busy} onClick={()=>sync()}>{busy==='all'?'Syncing…':'Sync all now'}</button>}</div></div>
  {open&&<form className="appleConnectForm" onSubmit={add}><label>Calendar name<input name="name" required maxLength="80" placeholder="Personal / Silkfutures"/></label><label className="wide">Apple subscription URL<input name="url" required type="url" placeholder="webcal://p…-caldav.icloud.com/published/…"/></label><label>Buffer before<select name="bufferBefore" defaultValue="0"><option value="0">None</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option></select></label><label>Buffer after<select name="bufferAfter" defaultValue="0"><option value="0">None</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option></select></label><label className="appleCheck"><input name="blockAllDay" type="checkbox" defaultChecked/> All-day events block the day</label><button className="button primary" disabled={busy==='add'}>{busy==='add'?'Connecting…':'Connect and sync'}</button></form>}
  {sources.length?<div className="appleSourceList">{sources.map(source=><article className="appleSource" key={source.id}><div><div className="appleSourceTitle"><b>{source.name}</b><span className={source.active?'active':'paused'}>{source.active?'ACTIVE':'PAUSED'}</span></div><small>{when(source.last_synced_at)} · {source.block_all_day?'All-day events included':'Timed events only'} · {source.buffer_before_minutes||source.buffer_after_minutes?`${source.buffer_before_minutes}m before / ${source.buffer_after_minutes}m after`:'No buffer'}</small>{source.last_error&&<p className="appleSyncError">Sync issue: {source.last_error}</p>}</div><div className="appleSourceActions"><button className="miniButton" disabled={!!busy} onClick={()=>sync(source.id)}>Sync</button><button className="miniButton" disabled={!!busy} onClick={()=>patch(source.id,{active:!source.active})}>{source.active?'Pause':'Resume'}</button><button className="miniButton danger" disabled={!!busy} onClick={()=>remove(source.id,source.name)}>Disconnect</button></div></article>)}</div>:<p className="appleEmpty">No outside calendars connected yet.</p>}
  {msg&&<p className="appleConnectMessage">{msg}</p>}
  <details className="appleSetupHelp"><summary>How to copy an Apple Calendar link</summary><ol><li>Open Apple Calendar on your Mac.</li><li>Control-click the calendar name and choose <b>Share Calendar</b>.</li><li>Turn on <b>Public Calendar</b>, then choose <b>Copy Link</b>.</li><li>Paste it above. Keep the copied link private.</li></ol></details>
 </div>
}
