import Link from 'next/link';
import SiteHeader from './SiteHeader';
import ArtistSupportApplication from './ArtistSupportApplication';
import GoogleReviewProof from './GoogleReviewProof';
const releases=[['Mace the Great','Splott World','https://open.spotify.com/album/0BqBh7Jzup3GF5hIjZe16Y'],['Sage Todz','King of the North','https://open.spotify.com/album/5ugFTvdY5kLOTzhBSJvrzQ'],['Lukey RV','Project contribution','https://open.spotify.com/album/7eOdhqN34gNPDBhUIcm7yC'],['Aleighcia Scott','Project contribution','https://open.spotify.com/album/3MRXMeqBfshEnRtnP29NeC'],['DIDE','Project contribution','https://open.spotify.com/album/40c3dqzKyHlparsgQ69dkU']];
const story=[['Before Cardiff','Nathan spent seven years pursuing music in London: developing as an artist, recording rappers from a home studio and learning from inside the scene.'],['London to Los Angeles','Three months in LA led to work alongside engineer Harry Chaplin, an apprentice to Beyoncé engineer DJ Swivel. Nathan and Harry then launched Silkcrayon first as a management company to develop and represent their own work.'],['The Cardiff studio','Finding the Cardiff Bay space changed the direction. From 2020, Silkcrayon became part of a surge in Welsh MOBO music: a studio, creative base and micro-scene where local artists could record, experiment and grow around one another.'],['A development ecosystem','Toni brought more than 25 years of youth-work experience through Lab7. Its partnership with Silkcrayon gave young artists professional creative space and trusted support; that shared method was later formalised through Silkfutures CIC.'],['Beyond Wales','Artists began travelling from Bristol, Birmingham and beyond for recording combined with artist development, executive production and honest direction. Silkcrayon later travelled to London to contribute to DIDE’s debut project and creative identity.']];
export default function ArtistDevelopmentStoryPage(){return <main className="marketingSite artistDevelopmentPage"><SiteHeader/>
<section className="artistDevHero"><div className="container"><p className="eyebrow">Artist development · Cardiff or online</p><h1>Make the music.<br/><span>Move it forward.</span></h1><p className="lede">Practical direction from people who have helped artists move from first sessions and unfinished catalogues towards stronger records, clearer identities and real releases.</p><div className="actions"><Link className="button primary" href="/booking?service=artist-development">Book 60 minutes · £75 →</Link><a className="textLink" href="#ongoing">Explore ongoing support ↓</a></div></div></section>
<section className="section artistProofIntro"><div className="container artistHistoryGrid"><div><p className="eyebrow">Why Silkcrayon</p><h2>This was built inside the work.</h2></div><div><p>Silkcrayon did not begin as a consultancy. It grew through recording sessions, artist relationships, releases, visual work, community building and the difficult middle where talented people need help turning potential into movement.</p><p>That experience is what you are paying for: a useful outside perspective grounded in what it actually takes to develop the work and keep going.</p><a className="textLink" href="https://www.walesonline.co.uk/whats-on/music-nightlife-news/silkcrayon-recording-studio-music-cardiff-25259278" target="_blank" rel="noreferrer">Read the WalesOnline Silkcrayon feature ↗</a></div></div></section>
<section className="section artistStory"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">The journey</p><h2>From home studio<br/>to artist ecosystem.</h2></div><p>A development practice shaped across London, Los Angeles, Cardiff and years of direct artist work.</p></div><div className="artistStoryTimeline">{story.map(([title,copy],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
<section className="section artistSceneProof"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">Part of the record</p><h2>Development you<br/>can listen to.</h2></div><p>Selected releases Silkcrayon contributed to across recording, production, writing, direction or wider artist development. The exact role differed by project.</p></div><div className="artistReleaseGrid">{releases.map(([artist,title,href],i)=><a key={href} href={href} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span><div><b>{artist}</b><small>{title}</small></div><em>Listen ↗</em></a>)}</div><p className="artistProofNote">The wider studio story also includes the 12-part Krayola performance series, visual work across rap and alternative music, and sessions with artists including Baddathanwho, Aleighcia Scott, Juice Menace, Sage Todz, KS24, Celo and Benny Flowz.</p></div></section>
<GoogleReviewProof context="artist-development"/>
<section className="section"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">Choose your adviser</p><h2>Creative direction<br/>or release structure.</h2></div><p>Choose the perspective that best matches the problem. If you are unsure, select no preference.</p></div><div className="adviserGrid"><article><div className="adviserImage"><img src="/images/artist-development/nathan.jpg" alt="Nathan, Silkcrayon creative development adviser"/></div><div><p className="eyebrow">Nathan · Creative development</p><h3>Shape the artist and the work.</h3><p>Best for song direction, catalogue decisions, creative identity, production priorities, confidence and working out what the music needs next.</p><ul><li>Choosing what to finish and release</li><li>Creative blocks and release fear</li><li>Sound, identity and project direction</li><li>Recording, production and mix priorities</li></ul></div></article><article><div className="adviserImage"><img src="/images/artist-development/toni.jpg" alt="Toni, Silkcrayon release planning adviser"/></div><div><p className="eyebrow">Toni · Release logistics</p><h3>Turn intention into a process.</h3><p>Best for organisation, accountability, distribution, Spotify setup, assets and building a manageable route from finished music to release day.</p><ul><li>Release timelines and accountability</li><li>Distribution and Spotify for Artists</li><li>Artwork, content and asset checklists</li><li>Keeping the release cycle organised</li></ul></div></article></div><div className="artistDevCta"><div><h3>Bring the backlog, block or unfinished plan.</h3><p>You do not need polished answers. Tell us where you are stuck and we will start there.</p></div><Link className="button primary" href="/booking?service=artist-development">Book for £75 →</Link></div></div></section>
<section className="section artistFuturesProof"><div className="container artistHistoryGrid"><div><p className="eyebrow">Silkcrayon × Silkfutures</p><h2>A method made repeatable.</h2></div><div><p>The partnership between Silkcrayon and Toni’s youth work developed into Silkfutures: music, mentoring and movement for young people. Five years of delivery helped formalise a pathway from expression and creative practice towards confidence, capability and leadership.</p><p>That work is separate from a private Artist Development booking, but its listening, structure and belief in artist ownership inform how Silkcrayon works.</p><a className="textLink" href="https://www.silkfutures.com/" target="_blank" rel="noreferrer">Explore Silkfutures ↗</a></div></div></section>
<section className="section" id="ongoing"><div className="container"><div className="sectionHeading"><div><p className="eyebrow">Ongoing release support</p><h2>Structure across<br/>the release cycle.</h2></div><p>For artists who want regular accountability and practical coordination. Apply first; scope and monthly price are agreed before anything begins.</p></div><div className="artistSupportScope"><p>Release planning and deadlines</p><p>Regular accountability check-ins</p><p>Distribution and profile guidance</p><p>Recording, mix and master coordination</p><p>Artwork and content coordination</p><p>Release review and next-cycle planning</p></div><ArtistSupportApplication/></div></section>
</main>}
