"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function LegacyCreditForm({customer,currentBalance=0}){
 const router=useRouter(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();const form=e.currentTarget,body=Object.fromEntries(new FormData(form).entries());if(!confirm(`Add ${body.hours} hours to ${customer.artist_name||customer.full_name} (${customer.email})?`))return;setBusy(true);setMsg('Adding credit…');const r=await fetch(`/api/admin/customers/${customer.id}/credits`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMsg(j.error||'Could not add credit.');setMsg(`Added ✓ New balance: ${j.balance}h${j.emailSent?' · confirmation emailed':''}`);setOpen(false);router.refresh()}
 return <section className="engSection legacyCreditSection"><div className="engSectionHead"><div><p className="eyebrow">Previous system</p><h2>Import existing credit</h2><p>Transfer a paid voucher or unused balance without charging the artist again or adding it to today’s revenue.</p></div><button className="miniButton solid" onClick={()=>setOpen(v=>!v)}>{open?'Close':'+ Add existing credit'}</button></div><div className="legacyBalance"><small>CURRENT BALANCE</small><b>{currentBalance}h</b><span>{customer.email}</span></div>{open&&<form className="legacyCreditForm" onSubmit={submit}><label>Studio hours<input name="hours" type="number" min="0.5" max="100" step="0.5" defaultValue="6" required/></label><label>Amount originally paid (£)<input name="amountPaid" type="number" min="0" step="0.01" defaultValue="300" required/></label><label className="wide">Old order / voucher reference<input name="reference" maxLength="120" placeholder="Wix gift card order #10123" required/></label><label className="wide">Internal note<input name="note" maxLength="300" placeholder="Gift from parents · transferred from old system"/></label><div className="legacyCreditWarning wide"><b>This immediately adds usable hours.</b><span>The artist will receive an email confirming the balance and can book through My Studio.</span></div><button className="button primary wide" disabled={busy}>{busy?'Adding…':'Confirm existing credit'}</button></form>}{msg&&<p className="legacyCreditMessage">{msg}</p>}</section>
}
