"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function LegacyCreditForm({customer,currentBalance=0}){
 const router=useRouter(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();if(busy)return;const form=e.currentTarget,body=Object.fromEntries(new FormData(form).entries());if(!confirm(`Add ${body.hours} hours to ${customer.artist_name||customer.full_name} (${customer.email})?`))return;setBusy(true);setMsg('Adding credit…');try{const r=await fetch(`/api/admin/customers/${customer.id}/credits`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not add credit.');setMsg(`Credit added. Balance: ${j.balance}h. ${j.emailWarning||(j.emailSent?'Email accepted by provider; see Automations.':'Email not sent.')}`);setOpen(false);router.refresh()}catch(e){setMsg(`${e.message} Refresh and check the balance before retrying.`)}finally{setBusy(false)}}
 async function resend(){if(busy||!confirm(`Send the voucher-credit email again to ${customer.email}? This does not add any credit.`))return;setBusy(true);setMsg('Sending email…');try{const r=await fetch(`/api/admin/customers/${customer.id}/credits/email`,{method:'POST'}),j=await r.json();setMsg(j.message||j.error||'Could not send email.');router.refresh()}catch{setMsg('Email result unknown. Check Automations before retrying.')}finally{setBusy(false)}}
 return <section className="engSection legacyCreditSection"><div className="engSectionHead"><div><p className="eyebrow">Previous system</p><h2>Import existing credit</h2><p>Transfer unused paid hours without taking a new payment. Check the original voucher terms before converting pounds into hours.</p></div><button className="miniButton solid" disabled={busy} onClick={()=>setOpen(v=>!v)}>{open?'Close':'+ Add existing credit'}</button></div><div className="legacyBalance"><small>CURRENT BALANCE</small><b>{currentBalance}h</b><span>{customer.email}</span></div><button type="button" className="miniButton" disabled={busy} onClick={resend}>Resend latest voucher email · no extra credit</button>{open&&<form className="legacyCreditForm" onSubmit={submit}><label>Unused studio hours<input name="hours" type="number" min="0.5" max="100" step="0.5" placeholder="Confirm hours to transfer" required/></label><label>Amount originally paid (£)<input name="amountPaid" type="number" min="0" step="0.01" required/></label><label className="wide">Old order / voucher reference<input name="reference" maxLength="120" placeholder="Old system and order number" required/></label><label className="wide">Internal note<input name="note" maxLength="300" placeholder="Original voucher terms and any hours already used"/></label><div className="legacyCreditWarning wide"><b>This immediately adds usable hours.</b><span>A confirmation email will be attempted and logged in Automations. Email failure does not undo the credit.</span></div><button className="button primary wide" disabled={busy}>{busy?'Adding…':'Confirm existing credit'}</button></form>}{msg&&<p role="status" aria-live="polite" className="legacyCreditMessage">{msg}</p>}</section>
}
