'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export default function OwnerReschedulePanel({booking}){
 const router=useRouter(),[open,setOpen]=useState(false),[date,setDate]=useState(booking.booking_date||''),[slots,setSlots]=useState([]),[start,setStart]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(next){setDate(next);setStart('');setSlots([]);setMsg('');if(!next)return;setBusy(true);const r=await fetch(`/api/admin/bookings/${booking.id}/availability?date=${encodeURIComponent(next)}`),j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMsg(j.error||'Could not load availability.');setSlots(j.slots||[]);if(!(j.slots||[]).length)setMsg('No available slots for this session length on that date.');}
 async function save(){if(!date||!start)return setMsg('Choose a date and available time.');if(!confirm(`Reschedule this session to ${date} at ${start}? The customer will be notified.`))return;setBusy(true);setMsg('Rescheduling…');const r=await fetch(`/api/admin/bookings/${booking.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({ownerReschedule:{date,start,note}})}),j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setMsg(j.error||'Could not reschedule.');setMsg('Session rescheduled and customer notified ✓');setOpen(false);router.refresh();}
 return <div className="ownerReschedule"><button className="engSecondaryAction" onClick={()=>{setOpen(v=>!v);if(!open&&!slots.length)load(date)}}>{open?'Close reschedule':'Reschedule session'}</button>{open&&<div className="sessionManageForm rescheduleForm"><h3>Reschedule session</h3><p>Payment and engineer assignment stay attached to this booking. Availability is checked before the move is saved.</p><label>New date<input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>load(e.target.value)}/></label><label>Available time<select value={start} disabled={busy||!slots.length} onChange={e=>setStart(e.target.value)}><option value="">Choose a time…</option>{slots.map(s=><option key={s.start} value={s.start}>{s.start}–{s.end}</option>)}</select></label><label>Note to customer / internal context<textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional — e.g. Sorry, we needed to move your session."/></label><button className="miniButton solid" disabled={busy||!start} onClick={save}>{busy?'Working…':'Confirm reschedule'}</button>{msg&&<p className="manageMessage">{msg}</p>}</div>}</div>
}
