"use client";
import {useMemo,useState} from 'react';
import ArtistSearchSelect from './ArtistSearchSelect';
const discounts=[['none','No extra discount'],['loyalty5','5% loyalty'],['approved10','10% approved']];
const perHour=h=>h>=10?50:h>=8?52.5:h>=5?55:60;
const packBase=h=>h===2?110:Math.round(h*perHour(h)*100)/100;
export default function PaymentCreateForm({customers=[],defaultCustomerId='',defaultAmount='',defaultDescription='',defaultPackage='',defaultKind=''}){
 const initialKind=defaultKind||defaultPackage?'package':'session';
 const [kind,setKind]=useState(initialKind);const [customerId,setCustomerId]=useState(defaultCustomerId);const [hours,setHours]=useState(Math.max(1,Math.min(20,Number(defaultPackage||5))));const [discountCode,setDiscountCode]=useState('none');const [manualAmount,setManualAmount]=useState(defaultAmount||'60');const [description,setDescription]=useState(defaultDescription||'Studio session');const [msg,setMsg]=useState('');
 const customer=useMemo(()=>customers.find(c=>c.id===customerId),[customers,customerId]);
 const discountPct=discountCode==='loyalty5'?5:discountCode==='approved10'?10:0;
 const standard=hours*60,bulk=packBase(hours),finalPack=Math.round(bulk*(1-discountPct/100)*100)/100;
 const mixBase=60,mixFinal=Math.round(mixBase*(1-discountPct/100)*100)/100;
 async function submit(){if(!customerId)return setMsg('Choose an artist first.');setMsg('Creating secure payment…');const body={customerId,kind,hours:kind==='package'?hours:0,discountCode,amount:kind==='session'||kind==='other'?manualAmount:undefined,description:kind==='package'?`${hours} prepaid studio hours`:kind==='mix_master'?'Studio Finish':description};const r=await fetch('/api/admin/payments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)return setMsg(j.error||'Could not create payment.');window.location.href=j.url}
 return <div className="commercialPayFlow">
  <section className="commercialStep"><div className="stepBadge">01</div><div><p className="eyebrow">Artist</p><h2>Who are we charging?</h2><ArtistSearchSelect customers={customers} value={customerId} onChange={setCustomerId}/>{customer&&<p className="selectionNote">Selected <b>{customer.artist_name||customer.full_name}</b></p>}</div></section>
  <section className="commercialStep"><div className="stepBadge">02</div><div><p className="eyebrow">Product</p><h2>What are they buying?</h2><div className="productTabs"><button type="button" className={kind==='package'?'active':''} onClick={()=>setKind('package')}>Studio hours</button><button type="button" className={kind==='mix_master'?'active':''} onClick={()=>setKind('mix_master')}>Studio Finish</button><button type="button" className={kind==='session'?'active':''} onClick={()=>setKind('session')}>Session</button><button type="button" className={kind==='other'?'active':''} onClick={()=>setKind('other')}>Other</button></div>
  {kind==='package'&&<div className="hoursBuilder"><div className="hoursHeadline"><div><small>PREPAID HOURS</small><b>{hours}</b></div><div className="hoursPrice"><small>PACKAGE PRICE</small><b>£{finalPack.toFixed(2)}</b><span>{standard>bulk?`£${standard.toFixed(2)} standard · save £${(standard-finalPack).toFixed(2)}`:`£60 / hour`}</span></div></div><div className="hoursControls"><button type="button" onClick={()=>setHours(Math.max(1,hours-1))}>−</button><input type="range" min="1" max="20" step="1" value={hours} onChange={e=>setHours(Number(e.target.value))}/><button type="button" onClick={()=>setHours(Math.min(20,hours+1))}>+</button></div><div className="tierRail"><span>2 hrs · £110</span><span>5–7 · £55/hr</span><span>8–9 · £52.50/hr</span><span>10+ · £50/hr</span></div></div>}
  {kind==='mix_master'&&<div className="mixProduct"><span className="mixIcon">〽</span><div><b>Studio Finish</b><p>A focused finishing pass after the session: cleanup, vocal polish, effect refinement and final master.</p><small>Delivered within 7 days · 1 revision</small></div><strong>£{mixFinal.toFixed(2)}</strong></div>}
  {(kind==='session'||kind==='other')&&<div className="manualCharge"><label className="field"><span>Amount (£)</span><input type="number" min="0.30" step="0.01" value={manualAmount} onChange={e=>setManualAmount(e.target.value)}/></label><label className="field"><span>Description</span><input value={description} onChange={e=>setDescription(e.target.value)}/></label></div>}</div></section>
  <section className="commercialStep"><div className="stepBadge">03</div><div><p className="eyebrow">Discount</p><h2>Apply an approved discount.</h2><div className="discountChooser">{discounts.map(([code,label])=><button type="button" key={code} className={discountCode===code?'active':''} onClick={()=>setDiscountCode(code)}>{label}</button>)}</div><p className="tiny muted">Package pricing is automatic. This discount is additional and is recorded against the payment.</p></div></section>
  <section className="checkoutDock"><div><small>TOTAL TO PAY</small><b>£{kind==='package'?finalPack.toFixed(2):kind==='mix_master'?mixFinal.toFixed(2):Number(manualAmount||0).toFixed(2)}</b></div><button type="button" className="engPrimaryAction buttonLike" onClick={submit}>Open secure checkout <span>→</span></button>{msg&&<p>{msg}</p>}</section>
 </div>;
}
