"use client";
import {useEffect,useMemo,useState} from 'react';
const packages=[{label:'2 studio hours',hours:2,amount:120},{label:'5 studio hours',hours:5,amount:275},{label:'10 studio hours',hours:10,amount:500}];
export default function PaymentCreateForm({customers=[],defaultCustomerId='',defaultAmount='',defaultDescription='',defaultPackage=''}){
 const initialPack=packages.find(p=>String(p.hours)===String(defaultPackage));
 const [kind,setKind]=useState(initialPack?'package':'session'); const [customerId,setCustomerId]=useState(defaultCustomerId); const [amount,setAmount]=useState(initialPack?String(initialPack.amount):(defaultAmount||'60')); const [hours,setHours]=useState(initialPack?String(initialPack.hours):'0'); const [description,setDescription]=useState(initialPack?initialPack.label:(defaultDescription||'Studio session')); const [msg,setMsg]=useState('');
 const customer=useMemo(()=>customers.find(c=>c.id===customerId),[customers,customerId]);
 function usePackage(p){setKind('package');setAmount(String(p.amount));setHours(String(p.hours));setDescription(p.label)}
 async function submit(e){e.preventDefault();setMsg('Creating secure payment…');const r=await fetch('/api/admin/payments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customerId,kind,amount,hours,description})});const j=await r.json();if(!r.ok){setMsg(j.error||'Could not create payment.');return;}window.location.href=j.url}
 return <div className="engPayFlow"><div className="engPayStep"><span>1</span><div><h3>Choose artist</h3><label className="field"><select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select artist</option>{customers.map(c=><option key={c.id} value={c.id}>{c.artist_name||c.full_name} · {c.email}</option>)}</select></label></div></div>
 <div className="engPayStep"><span>2</span><div><h3>What are they paying for?</h3><div className="packageGrid">{packages.map(p=><button type="button" key={p.hours} className={`quickTile ${kind==='package'&&Number(hours)===p.hours?'selected':''}`} onClick={()=>usePackage(p)}><small>PREPAID</small><b>{p.hours} HOURS</b><span>£{p.amount}</span></button>)}</div><button type="button" className={`engSessionCharge ${kind==='session'?'selected':''}`} onClick={()=>{setKind('session');setHours('0');setDescription('Studio session')}}>Charge a single session</button></div></div>
 <form className="engPayStep last" onSubmit={submit}><span>3</span><div><h3>Confirm amount</h3>{customer&&<p className="selectionNote">Charging <b>{customer.artist_name||customer.full_name}</b></p>}<div className="engAmountRow"><label className="field"><span>Amount (£)</span><input type="number" min="0.30" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>Description</span><input required value={description} onChange={e=>setDescription(e.target.value)}/></label></div><button className="engPrimaryAction buttonLike">Open secure checkout <span>→</span></button><p className="tiny muted">The customer can pay on this phone using the payment methods enabled in Stripe.</p>{msg&&<p className="muted">{msg}</p>}</div></form></div>
}
