'use client';
import {useState} from 'react';import {createBrowserClient} from '@supabase/ssr';
const client=()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
export default function PublicMixRequestForm(){
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[done,setDone]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setMsg('Creating your request…');try{const fd=new FormData(e.currentTarget),files=fd.getAll('files').filter(x=>x?.size),body=Object.fromEntries(fd.entries());delete body.files;const r=await fetch('/api/mix-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error);for(let i=0;i<files.length;i++){const file=files[i];setMsg(`Uploading ${i+1} of ${files.length}: ${file.name}`);const p=await fetch('/api/mix-requests',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({jobId:j.id,uploadToken:j.uploadToken,fileName:file.name,contentType:file.type,size:file.size,fileKind:i===0?'rough_mix':'other'})}),pj=await p.json();if(!p.ok)throw new Error(pj.error);const {error}=await client().storage.from(pj.bucket).uploadToSignedUrl(pj.path,pj.token,file,{contentType:file.type||'application/octet-stream'});if(error)throw error;const saved=await fetch('/api/mix-requests',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({jobId:j.id,uploadToken:j.uploadToken,path:pj.path,fileName:file.name,size:file.size,fileKind:pj.fileKind})});if(!saved.ok)throw new Error('The file uploaded but could not be attached. Please contact the studio.')}setDone(true);setMsg('')}catch(err){setMsg(err.message)}finally{setBusy(false)}}
 if(done)return <div className="portalNotice success"><b>Mix request received.</b><span>We’ll listen, check what the track needs and email you a tailored quote. If we need different files, we’ll explain exactly what to send.</span></div>;
 return <form className="mixRequestForm" onSubmit={submit}><div className="mixFormGrid"><label className="field"><span>Your name</span><input name="fullName" required/></label><label className="field"><span>Artist name <small>Optional</small></span><input name="artistName"/></label><label className="field"><span>Email</span><input name="email" type="email" required/></label><label className="field"><span>Mobile number <small>Optional</small></span><input name="phone"/></label><label className="field"><span>Track title</span><input name="trackTitle" required/></label><label className="field"><span>What do you need?</span><select name="serviceType" defaultValue="not_sure"><option value="not_sure">Not sure — recommend what I need</option><option value="mix_only">Mix only</option><option value="mix_master">Mix + master</option><option value="master_only">Master only</option></select></label><label className="field wide"><span>What would you like help with?</span><textarea name="clientBrief" rows="5" required placeholder="Tell us how the track sounds now, what is bothering you and how you want it to feel when it is finished."/></label><label className="deliveryFile wide"><span>Upload whatever you currently have</span><input type="file" name="files" multiple required/><small>A rough MP3 or WAV is enough to start. You can also send stems or a session export if you already have them. If you are unsure, we’ll tell you what else we need after listening.</small></label></div><details className="mixOptionalDetails"><summary>Extra track details <span>Optional — leave anything you don’t know blank</span></summary><div className="mixFormGrid"><label className="field"><span>Genre / style <small>Optional</small></span><input name="genre"/></label><label className="field"><span>Release date <small>Only if you have one</small></span><input name="releaseDate" type="date"/></label><label className="field"><span>BPM <small>Leave blank if you don’t know</small></span><input name="bpm" inputMode="numeric"/></label><label className="field"><span>Key <small>Leave blank if you don’t know</small></span><input name="musicalKey"/></label><label className="field wide"><span>Reference tracks <small>Optional</small></span><textarea name="referenceTracks" rows="3" placeholder="Songs or links that show the sound you like"/></label><label className="checkField"><input type="checkbox" name="vocalTuningEditing"/><span>I may need vocal tuning or editing</span></label><label className="checkField"><input type="checkbox" name="stemDelivery"/><span>I may need separate mix stems delivered</span></label></div></details><label className="checkField mixPermission"><input type="checkbox" required/><span>I have permission to submit this material and agree to be contacted about this quote.</span></label><button className="button primary" disabled={busy}>{busy?'Uploading…':'Submit for a quote →'}</button>{msg&&<p className="deliveryMessage">{msg}</p>}</form>
}
