import Link from "next/link";
import SiteHeader from "./SiteHeader";
import Reveal from "./Reveal";
export default function SeoServicePage({eyebrow,title,accent,intro,points,ctaHref="/booking",cta="Book a session",image="/images/wide.webp",imageAlt}){
 return <main className="marketingSite seoLanding"><SiteHeader/>
 <section className="seoHero"><div className="container seoHeroGrid"><Reveal><div><p className="eyebrow">{eyebrow}</p><h1>{title}<br/><span>{accent}</span></h1><p className="lede">{intro}</p><div className="actions"><Link className="button primary magnetic" href={ctaHref}>{cta} <span>↗</span></Link><Link className="textLink" href="/enquire">Make an enquiry →</Link></div></div></Reveal><Reveal delay={100}><div className="seoHeroImage"><img src={image} alt={imageAlt}/><div className="seoHeroBadge"><b>Silkcrayon Studios</b><span>Cardiff Bay · Wales</span></div></div></Reveal></div></section>
 <section className="section seoReasons"><div className="container"><Reveal><div className="sectionHeading"><div><p className="eyebrow">At Silkcrayon</p><h2>Built for the work,<br/>not just the booking.</h2></div><p>Professional studio standards with a creative process that keeps the artist and the outcome at the centre.</p></div></Reveal><div className="seoPointGrid">{points.map((p,i)=><Reveal key={p.title} delay={i*60}><article><span>0{i+1}</span><h3>{p.title}</h3><p>{p.copy}</p></article></Reveal>)}</div></div></section>
 <section className="section seoLocal"><div className="container seoLocalGrid"><Reveal><div><p className="eyebrow">Cardiff Bay</p><h2>A professional creative space in Cardiff.</h2></div></Reveal><Reveal delay={80}><div><p>Silkcrayon is based in Cardiff Bay and works with artists and creators from Cardiff, South Wales and beyond. Book studio time online or send us the project if you need a more tailored production service.</p><div className="actions"><Link className="button primary" href={ctaHref}>{cta} <span>↗</span></Link><Link className="textLink" href="/services">See all services →</Link></div></div></Reveal></div></section>
 <section className="section finalCta"><div className="container"><Reveal><p className="eyebrow">Silkcrayon Studios · Cardiff</p><h2>Ready when you are.</h2><p>Come with the idea. Leave with the work further forward.</p><Link className="button primary large" href={ctaHref}>{cta} <span>↗</span></Link></Reveal></div></section>
 <footer className="siteFooter"><div className="container footerGrid"><div><img src="/logo.png" alt="Silkcrayon"/><p>Cardiff Bay · Recording & creative development</p></div><div><Link href="/services">Services</Link><Link href="/#space">The Space</Link><Link href="/booking">Book</Link></div><div><Link href="/contact">Contact</Link><Link href="/faq">FAQ</Link><a href="https://instagram.com/silkcrayon" target="_blank" rel="noreferrer">Instagram ↗</a></div></div></footer><Link href="/booking" className="mobileBookBar">Book a session <span>↗</span></Link></main>
}