import Link from "next/link";
import SiteHeader from "./SiteHeader";
import Reveal from "./Reveal";
import {getLivePromotions,publicPromotion} from "../lib/promotions";

export default async function SeoServicePage({
 eyebrow,title,accent,intro,points,ctaHref="/booking",cta="Book a session",image="/images/wide.webp",imageAlt,
 proof=[],storyTitle="A studio built around the artist.",story=[],storyImage="/images/workstation.webp",storyImageAlt="Silkcrayon Studios Cardiff",
 process=[],related=[],showPromotion=false
}){
 const promo=showPromotion?publicPromotion((await getLivePromotions()).find(p=>p.show_on_booking&&p.service_slug==='vocal-recording')):null;
 return <main className="marketingSite seoLanding seoLandingV2"><SiteHeader/>
  <section className="seoHero seoHeroV2"><div className="container seoHeroGrid"><Reveal><div className="seoHeroText"><p className="eyebrow">{eyebrow}</p><h1>{title}<br/><span>{accent}</span></h1><p className="lede">{intro}</p><div className="actions"><Link className="button primary magnetic" href={ctaHref}>{cta} <span>↗</span></Link><Link className="textLink" href="/request-a-call">Talk it through →</Link></div>{proof.length>0&&<div className="seoProof">{proof.map(x=><span key={x}>{x}</span>)}</div>}</div></Reveal><Reveal delay={100}><div className="seoHeroImage"><img src={image} alt={imageAlt}/><div className="seoHeroImageShade"/><div className="seoHeroBadge"><b>Silkcrayon Studios</b><span>Cardiff Bay · Wales</span></div></div></Reveal></div></section>

  {promo&&<section className="seoPromo"><div className="container seoPromoInner"><div><p className="eyebrow">Current studio offer</p><h2>{promo.durationMinutes/60} hours for <span>£{promo.offerPricePence/100}</span></h2><p>Usually £{promo.normalPricePence/100}. {promo.description||'Book the same Silkcrayon vocal session at the current promotional rate.'}</p></div><div className="seoPromoPrice"><s>£{promo.normalPricePence/100}</s><strong>£{promo.offerPricePence/100}</strong><Link className="button primary" href={`/booking?service=${promo.serviceSlug}&duration=${promo.durationMinutes}`}>{promo.ctaText||'Book the offer'} <span>↗</span></Link></div></div></section>}

  <section className="section seoReasons"><div className="container"><Reveal><div className="sectionHeading"><div><p className="eyebrow">Why Silkcrayon</p><h2>More than a room<br/>and a microphone.</h2></div><p>The equipment matters. What matters more is having an engineer, environment and process that help you make stronger work.</p></div></Reveal><div className="seoPointGrid">{points.map((p,i)=><Reveal key={p.title} delay={i*60}><article><span>0{i+1}</span><h3>{p.title}</h3><p>{p.copy}</p></article></Reveal>)}</div></div></section>

  {story.length>0&&<section className="section seoStory"><div className="container seoStoryGrid"><Reveal><div className="seoStoryImage"><img src={storyImage} alt={storyImageAlt}/></div></Reveal><Reveal delay={100}><div className="copyBlock"><p className="eyebrow">The session</p><h2>{storyTitle}</h2>{story.map((p,i)=><p key={i}>{p}</p>)}<Link className="textLink" href="/services">Explore all studio services →</Link></div></Reveal></div></section>}

  {process.length>0&&<section className="section seoProcess"><div className="container"><Reveal><div className="sectionHeading"><div><p className="eyebrow">How it works</p><h2>Simple from idea<br/>to finished work.</h2></div></div></Reveal><div className="seoProcessGrid">{process.map((p,i)=><Reveal key={p.title} delay={i*65}><article><span>{String(i+1).padStart(2,'0')}</span><h3>{p.title}</h3><p>{p.copy}</p></article></Reveal>)}</div></div></section>}

  <section className="section seoLocal"><div className="container seoLocalGrid"><Reveal><div><p className="eyebrow">Cardiff Bay</p><h2>Hidden inside a<br/><span>1926 bank vault.</span></h2></div></Reveal><Reveal delay={80}><div><p>Silkcrayon is based in Cardiff Bay and works with artists and creators from across Cardiff, South Wales and beyond. The space combines a dedicated vocal booth, professional monitoring and hands-on engineering in an environment designed to feel creative rather than clinical.</p><div className="actions"><Link className="button primary" href={ctaHref}>{cta} <span>↗</span></Link><Link className="textLink" href="/getting-here">Getting here →</Link></div></div></Reveal></div></section>

  {related.length>0&&<section className="section seoRelated"><div className="container"><p className="eyebrow">Keep exploring</p><div className="seoRelatedGrid">{related.map(r=><Link href={r.href} key={r.href}><small>{r.kicker||'Silkcrayon'}</small><b>{r.title}</b><span>{r.copy||'Explore →'}</span></Link>)}</div></div></section>}

  <section className="section finalCta"><div className="container"><Reveal><p className="eyebrow">Silkcrayon Studios · Cardiff</p><h2>Make the next one here.</h2><p>Choose a session, pick a time and come make something worth keeping.</p><Link className="button primary large" href={ctaHref}>{cta} <span>↗</span></Link><p className="ctaMicro">Cardiff Bay · Engineer included · Secure online booking</p></Reveal></div></section>
  <footer className="siteFooter"><div className="container footerGrid"><div><img src="/logo.png" alt="Silkcrayon"/><p>Cardiff Bay · Recording & creative development</p></div><div><Link href="/services">Services</Link><Link href="/recording-studio-cardiff">Recording studio Cardiff</Link><Link href="/vocal-recording-cardiff">Vocal recording Cardiff</Link><Link href="/music-production-cardiff">Music production Cardiff</Link></div><div><Link href="/contact">Contact</Link><Link href="/getting-here">Getting here</Link><Link href="/faq">FAQ</Link><a href="https://instagram.com/silkcrayon" target="_blank" rel="noreferrer">Instagram ↗</a></div></div></footer><Link href="/booking" className="mobileBookBar">Book a session <span>↗</span></Link></main>
}
