"use client";
import { useState } from 'react';
import { useSearchParams,useRouter } from 'next/navigation';
export default function SessionReportForm({bookings=[],staff=[],profile}){
 const params=useSearchParams(); const initial=params.get('booking')||''; const [msg,setMsg]=useState(''); const [bookingId,setBookingId]=useState(initial); const selected=bookings.find(b=>b.id===bookingId); const engineerMode=profile?.role==='engineer'; const fixedEngineer=profile?.engineer_name||profile?.full_name||''; const router=useRouter();
 async function submit(e){e.preventDefault();setMsg('Saving…');const fd=new FormData(e.currentTarget);const r=await fetch('/api/admin/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))});const j=await r.json();if(!r.ok){setMsg(j.error||'Could not save.');return;}setMsg('Session saved.');if(engineerMode)setTimeout(()=>router.push('/admin/engineer'),450);else{e.currentTarget.reset();setBookingId('')}}
 if(engineerMode)return <form className="engReportFlow" onSubmit={submit}>
   <section className="engReportStep"><span className="stepNo">1</span><div><h3>Which session?</h3><p>Choose the booking, or use manual for a walk-in.</p><label className="field"><select name="bookingId" value={bookingId} onChange={e=>setBookingId(e.target.value)}><option value="">Manual / walk-in</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.booking_date} {String(b.start_time).slice(0,5)} — {b.customers?.artist_name||b.customers?.full_name}</option>)}</select></label></div></section>
   <section className="engReportStep"><span className="stepNo">2</span><div><h3>Session basics</h3><div className="engTwoCols"><label className="field"><span>Artist</span><input name="artistName" required defaultValue={selected?.customers?.artist_name||selected?.customers?.full_name||''} key={'a'+bookingId}/></label><label className="field"><span>Date</span><input name="sessionDate" type="date" required defaultValue={selected?.booking_date||new Date().toISOString().slice(0,10)} key={'d'+bookingId}/></label><label className="field"><span>Actual hours</span><input name="actualHours" type="number" step="0.25" min="0.25" required defaultValue={selected?selected.duration_minutes/60:''} key={'h'+bookingId}/></label><label className="field"><span>Session value (£)</span><input name="studioFee" type="number" step="0.01" min="0" defaultValue={selected?(selected.amount_pence/100).toFixed(2):''} key={'f'+bookingId}/></label></div><input type="hidden" name="engineer" value={fixedEngineer}/><input type="hidden" name="startTime" value={selected?String(selected.start_time).slice(0,5):''}/><input type="hidden" name="paymentMethod" value="Stripe"/><input type="hidden" name="engineerFee" value="0"/></div></section>
   <section className="engReportStep"><span className="stepNo">3</span><div><h3>What happened?</h3><label className="field"><span>What did you work on?</span><textarea name="workCompleted" rows="3" placeholder="Vocals, layers, writing, mix changes…"/></label><label className="field"><span>Files safe?</span><input name="filesStatus" placeholder="Saved to artist folder / bounce exported…"/></label><label className="field"><span>Next move</span><input name="followUp" placeholder="Rebook, send mix, finish vocals…"/></label><label className="field"><span>Private note</span><textarea name="notes" rows="2" placeholder="Optional internal note"/></label></div></section>
   <button className="engPrimaryAction buttonLike fullAction">Finish & save session <span>✓</span></button>{msg&&<div className="engSaveMsg">{msg}</div>}
 </form>;
 return <form className="reportForm" onSubmit={submit}><label className="field full"><span>Booking</span><select name="bookingId" value={bookingId} onChange={e=>setBookingId(e.target.value)}><option value="">Manual / walk-in session</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.booking_date} {String(b.start_time).slice(0,5)} — {b.customers?.artist_name||b.customers?.full_name}</option>)}</select></label><div className="formGrid"><label className="field"><span>Engineer</span><select name="engineer" required defaultValue=""><option value="" disabled>Select engineer</option>{staff.map(s=><option key={s.user_id} value={s.engineer_name||s.full_name}>{s.engineer_name||s.full_name}</option>)}</select></label><label className="field"><span>Artist name</span><input name="artistName" required defaultValue={selected?.customers?.artist_name||selected?.customers?.full_name||''} key={'a'+bookingId}/></label><label className="field"><span>Date</span><input name="sessionDate" type="date" required defaultValue={selected?.booking_date||''} key={'d'+bookingId}/></label><label className="field"><span>Start time</span><input name="startTime" type="time" defaultValue={selected?String(selected.start_time).slice(0,5):''} key={'t'+bookingId}/></label><label className="field"><span>Actual hours</span><input name="actualHours" type="number" step="0.25" min="0.25" required defaultValue={selected?selected.duration_minutes/60:''} key={'h'+bookingId}/></label><label className="field"><span>Payment method</span><select name="paymentMethod"><option>Stripe</option><option>Cash</option><option>Bank Transfer</option><option>Complimentary</option><option>Other</option></select></label><label className="field"><span>Engineer fee (£)</span><input name="engineerFee" type="number" step="0.01" min="0"/></label><label className="field"><span>Studio fee / session value (£)</span><input name="studioFee" type="number" step="0.01" min="0" defaultValue={selected?(selected.amount_pence/100).toFixed(2):''} key={'f'+bookingId}/></label><label className="field full"><span>What did you work on?</span><textarea name="workCompleted" rows="3"/></label><label className="field full"><span>Files / project status</span><input name="filesStatus"/></label><label className="field full"><span>Follow-up</span><input name="followUp"/></label><label className="field full"><span>Internal notes</span><textarea name="notes" rows="3"/></label></div><button className="button primary">Save session report</button>{msg&&<p className="muted">{msg}</p>}</form>
}
