import Link from 'next/link';
import AdminNav from '../../../components/AdminNav';
import {EngineerHeader,EngineerBottomNav} from '../../../components/EngineerShell';
import SessionReportForm from '../../../components/SessionReportForm';
import { getAdminDb } from '../../../lib/supabase';
import { requireStaff } from '../../../lib/auth';
export const dynamic='force-dynamic';
export default async function Sessions({searchParams}){
 const ctx=await requireStaff(); const sp=await searchParams; const db=getAdminDb(); const from=new Date(Date.now()-86400000).toISOString().slice(0,10); const eng=ctx.profile.role==='engineer';
 let bookingQuery=db.from('bookings').select('*,customers(full_name,artist_name)').gte('booking_date',from).order('booking_date').order('start_time'); let reportQuery=db.from('session_reports').select('*').order('session_date',{ascending:false}).limit(100);
 if(eng){bookingQuery=bookingQuery.eq('engineer_user_id',ctx.user.id);reportQuery=reportQuery.eq('submitted_by_user_id',ctx.user.id)}
 const [{data:bookings=[]},{data:reports=[]},{data:staff=[]}]=await Promise.all([bookingQuery,reportQuery,eng?Promise.resolve({data:[]}):db.from('staff_profiles').select('user_id,full_name,engineer_name').eq('role','engineer').eq('active',true).order('full_name')]);
 return <main className={eng?'engApp':'adminPage'}>{eng?<EngineerHeader profile={ctx.profile} eyebrow="Session report"/>:<header className="adminHeader"><div><p className="eyebrow">Silkcrayon OS</p><h1>Sessions</h1><p className="muted">Complete and review engineer session reports.</p></div><AdminNav profile={ctx.profile}/></header>}
   {eng?<><section className="engWelcome compact"><div className="sessionsTopAction"><div><p className="eyebrow">Finish strong</p><h1>Complete the session.</h1><p>Keep it quick: confirm the booking, say what happened, make sure the files are safe, and note the next move.</p></div><Link href="/admin/bookings/new" className="button primary">+ New booking</Link></div></section><section className="engSection"><SessionReportForm bookings={bookings} staff={staff} profile={ctx.profile}/></section><section className="engSection"><div className="engSectionHead"><div><h2>Recent reports</h2><p>Your completed sessions.</p></div></div>{reports.slice(0,6).map(r=><article className="engHistoryRow" key={r.id}><div><b>{r.artist_name}</b><small>{r.session_date} · {r.actual_hours}h</small></div><p>{r.work_completed||'Session logged.'}</p></article>)}</section><EngineerBottomNav profile={ctx.profile}/></>:<><section className="adminSection"><div className="adminSectionHead"><div><p className="eyebrow">Engineer workflow</p><h2>Complete a session report</h2></div><Link href="/admin/bookings/new" className="button primary">+ New booking</Link></div><SessionReportForm bookings={bookings} staff={staff} profile={ctx.profile}/></section><section className="adminSection"><p className="eyebrow">History</p><h2>Recent reports</h2><div className="tableWrap"><table><thead><tr><th>Date</th><th>Artist</th><th>Engineer</th><th>Hours</th><th>Project status</th><th>Files</th></tr></thead><tbody>{reports.length?reports.map(r=><tr key={r.id}><td>{r.session_date}</td><td><b>{r.artist_name}</b></td><td>{r.engineer}</td><td>{r.actual_hours}</td><td>{String(r.project_status||r.follow_up||'—').replaceAll('_',' ')}</td><td>{r.files_status||'—'}</td></tr>):<tr><td colSpan="6">No reports yet.</td></tr>}</tbody></table></div></section></>}</main>
}
