import {formatUkDateTime} from '../../../../../lib/dates';
import Link from 'next/link';
import {requireStaff} from '../../../../../lib/auth';
import {getAdminDb} from '../../../../../lib/supabase';
import {formatGBP} from '../../../../../lib/services';
import {EngineerHeader,EngineerBottomNav} from '../../../../../components/EngineerShell';
import SessionLifecycleActions from '../../../../../components/SessionLifecycleActions';
import SessionUpsellPanel from '../../../../../components/SessionUpsellPanel';
import OwnerReschedulePanel from '../../../../../components/OwnerReschedulePanel';
import {BookingPaymentAction} from '../../../../../components/AdminActions';
import {getStudioSettings} from '../../../../../lib/studioSettings';
import SessionDeliveryPanel from '../../../../../components/SessionDeliveryPanel';
import AdditionalSessionPayment from '../../../../../components/AdditionalSessionPayment';
export const dynamic='force-dynamic';
function instagramHref(value){const v=String(value||'').trim();if(!v)return null;if(/^https?:\/\//i.test(v))return v;const handle=v.replace(/^@/,'').replace(/^instagram\.com\//i,'').replace(/\/$/,'');return handle?`https://instagram.com/${encodeURIComponent(handle)}`:null}
export default async function SessionFlow({params}){
 const ctx=await requireStaff(); const {id}=await params; const db=getAdminDb(); const pricing=await getStudioSettings();
 const [{data:b},{data:events=[]},{data:extraPayments=[]},{data:reports=[]}]=await Promise.all([db.from('bookings').select('*,customers(*)').eq('id',id).single(),db.from('booking_events').select('*').eq('booking_id',id).order('created_at',{ascending:false}).limit(12),db.from('studio_payments').select('id,description,amount_pence,status,payment_method,paid_at,session_hours').eq('booking_id',id).eq('payment_category','extra_time').order('created_at',{ascending:false}),db.from('session_reports').select('id,actual_hours,session_date').eq('booking_id',id).order('created_at',{ascending:false}).limit(1)]);
 if(!b)return <main className="engApp"><EngineerHeader profile={ctx.profile}/><div className="engEmpty"><b>Session not found.</b><Link href="/admin/engineer">Back to today</Link></div><EngineerBottomNav profile={ctx.profile}/></main>;
 if(ctx.profile.role==='engineer'&&b.engineer_user_id&&b.engineer_user_id!==ctx.user.id)return <main className="engApp"><EngineerHeader profile={ctx.profile}/><div className="engEmpty"><b>This session is assigned to another engineer.</b></div><EngineerBottomNav profile={ctx.profile}/></main>;
 const c=b.customers; const paid=b.payment_status==='paid'; const dryHire=b.service_slug==='dry-hire';
 return <main className="engApp">
   <EngineerHeader profile={ctx.profile} eyebrow="Live session"/>
   <section className="engFlowHero"><Link href="/admin/engineer" className="backLink">← Today</Link><div className={`engLiveBadge ${b.status}`}><span></span> {String(b.status).replaceAll('_',' ').toUpperCase()}</div><h1>{c?.artist_name||c?.full_name}</h1><p>{String(b.start_time).slice(0,5)}–{String(b.end_time).slice(0,5)} · {b.duration_minutes/60} hr · {b.service_name}</p></section>
   <section className="engFlowCard"><div className="engFlowTitle"><span>01</span><div><h2>Session brief</h2><p>What the artist told us before the session.</p></div><Link href={`/admin/artists/${c?.id}`}>View profile →</Link></div><div className="engArtistSummary"><div className="engAvatar big">{(c?.artist_name||c?.full_name||'?').slice(0,1).toUpperCase()}</div><div><b>{c?.artist_name||c?.full_name}</b>{c?.phone?<div className="sessionContactActions"><a href={`tel:${String(c.phone).replace(/\s+/g,'')}`}>Call {c.phone}</a><a href={`sms:${String(c.phone).replace(/\s+/g,'')}`}>Text</a></div>:<small>{c?.email}</small>}</div></div><div className="sessionBriefGrid"><div><small>Genre / style</small><b>{b.genre||c?.preferred_genre||'—'}</b></div><div><small>Instagram / social</small>{instagramHref(c?.instagram)?<a className="sessionSocialLink" href={instagramHref(c.instagram)} target="_blank" rel="noreferrer">{c.instagram} ↗</a>:<b>—</b>}</div><div className="wide"><small>What are they making?</small><p>{b.notes||'No customer note added.'}</p></div></div>{dryHire?<div className="dryHireSessionNotice"><b>DRY HIRE · NO SILKCRAYON ENGINEER</b><span>The customer or their own engineer runs the session. Studio access and equipment remain subject to the Dry Hire Terms.</span></div>:!b.engineer_user_id&&<div className="unassignedSessionNotice"><b>⚠ Engineer not assigned</b><span>If nobody is assigned before the reminder runs, Studio OS will assign the default owner/engineer before the customer is contacted.</span></div>}{b.preferred_engineer_name&&<div className="preferredEngineerNote"><b>★ Preferred engineer</b><span>{b.preferred_engineer_name}{b.engineer_user_id&&b.preferred_engineer_user_id!==b.engineer_user_id?' · current assignment differs':''}</span></div>}</section>
   <section className="engFlowCard"><div className="engFlowTitle"><span>02</span><div><h2>Payment</h2><p>Make sure the session is covered.</p></div></div><div className={`engPaymentState ${paid?'paid':'due'}`}><div><small>{paid?'ORIGINAL BOOKING PAID':'AMOUNT DUE'}</small><b>{formatGBP(b.amount_pence)}</b></div><span>{paid?'✓':'!'}</span></div>{!paid&&<><Link href={`/admin/payments?customer=${c?.id}&amount=${(b.amount_pence/100).toFixed(2)}&description=${encodeURIComponent(b.service_name)}`} className="engPrimaryAction">Take payment <span>→</span></Link>{ctx.profile.role==='owner'&&<BookingPaymentAction booking={b}/>}</>}{reports[0]&&Number(reports[0].actual_hours)>Number(b.duration_minutes)/60&&<div className="extraTimeSummary"><small>ACTUAL SESSION</small><b>{b.duration_minutes/60}h booked · {Number(reports[0].actual_hours)}h worked</b><span>+{Number(reports[0].actual_hours)-Number(b.duration_minutes)/60}h additional time</span></div>}{ctx.profile.role==='owner'&&<AdditionalSessionPayment bookingId={b.id} hourlyPrice={dryHire?40:pricing.studioHourlyPricePence/100} extraHours={reports[0]?Math.max(.25,Number(reports[0].actual_hours)-Number(b.duration_minutes)/60):1} payments={extraPayments}/>}</section>
   {['pending','confirmed','completed'].includes(b.status)&&<section className="engFlowCard"><div className="engFlowTitle"><span>03</span><div><h2>Finish the session</h2><p>Report, deliver files, then set up the next move.</p></div></div>{['pending','confirmed'].includes(b.status)&&<Link href={`/admin/sessions?booking=${b.id}`} className="engPrimaryAction">Complete session report <span>→</span></Link>}<div className="deliverySection"><p className="eyebrow">Files ready</p><h3>Deliver the work.</h3><p>Upload the finished file or paste the Drive / Dropbox / WeTransfer link. Silkcrayon will email and text the customer automatically.</p><SessionDeliveryPanel bookingId={b.id}/></div>{!dryHire&&<SessionUpsellPanel customerId={c?.id} hourlyPrice={pricing.studioHourlyPricePence/100} studioFinishPrice={pricing.studioFinishPricePence/100} relaunchPrice={pricing.relaunchOfferPricePence/100}/>}</section>}
   <section className="engFlowCard">{ctx.profile.role==='owner'&&['pending','confirmed'].includes(b.status)&&<div className="sessionQuickTools"><OwnerReschedulePanel booking={b}/><a className="engSecondaryAction" href={`/api/admin/bookings/${b.id}/calendar`}>Add to calendar</a></div>}<SessionLifecycleActions booking={b} role={ctx.profile.role}/></section>
   {events.length>0&&<section className="engFlowCard"><div className="engFlowTitle"><span>↻</span><div><h2>Activity</h2><p>Permanent booking history.</p></div></div><div className="miniTimeline">{events.map(e=><div key={e.id}><span></span><p><b>{String(e.event_type).replaceAll('_',' ')}</b><small>{formatUkDateTime(e.created_at)}{e.reason_code?` · ${String(e.reason_code).replaceAll('_',' ')}`:''}</small>{e.note&&<em>{e.note}</em>}</p></div>)}</div></section>}
   <EngineerBottomNav profile={ctx.profile}/>
 </main>
}
