import Link from 'next/link';
import {requireStaff} from '../../../lib/auth';
import {getAdminDb} from '../../../lib/supabase';
import {EngineerHeader,EngineerBottomNav} from '../../../components/EngineerShell';
export const dynamic='force-dynamic';
function addDays(dateStr,days){const d=new Date(dateStr+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function niceDay(dateStr,today){if(dateStr===today)return 'TODAY';if(dateStr===addDays(today,1))return 'TOMORROW';return new Date(dateStr+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'}).toUpperCase()}
function Card({b,today}){return <article className="engSessionCard future"><div className="engSessionMeta"><span className="statusDot"></span><small>{niceDay(b.booking_date,today)}</small><b>{String(b.start_time).slice(0,5)}</b><small>{b.duration_minutes/60} hr</small></div><div className="engSessionMain"><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.service_name}</p><div className="engSessionBadges"><span className={b.payment_status==='paid'?'paid':'due'}>{b.payment_status==='paid'?'Paid':'Payment due'}</span></div><Link href={`/admin/engineer/session/${b.id}`} className="engPrimaryAction">{b.booking_date===today?'Start session':'View session'} <span>→</span></Link></div></article>}
export default async function EngineerHome(){
 const ctx=await requireStaff(); const db=getAdminDb(); const today=new Date().toISOString().slice(0,10),until=addDays(today,14);
 let q=db.from('bookings').select('*,customers(id,full_name,artist_name,email,phone)').gte('booking_date',today).lte('booking_date',until).in('status',['pending','confirmed']).order('booking_date').order('start_time');
 if(ctx.profile.role==='engineer')q=q.eq('engineer_user_id',ctx.user.id);
 const [{data:bookings=[]},{data:recent=[]}]=await Promise.all([q,db.from('session_reports').select('id,artist_name,session_date,actual_hours').eq('submitted_by_user_id',ctx.user.id).order('created_at',{ascending:false}).limit(3)]);
 const todayBookings=bookings.filter(b=>b.booking_date===today),future=bookings.filter(b=>b.booking_date>today),first=(ctx.profile.full_name||'').split(' ')[0];
 return <main className="engApp"><EngineerHeader profile={ctx.profile}/><section className="engWelcome"><p className="eyebrow">Engineer dashboard</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, {first}.</h1><p>Your sessions, artists and payments — nothing else.</p></section>
 <section className="engSection"><div className="engSectionHead"><div><h2>Today</h2><p>{todayBookings.length?`${todayBookings.length} session${todayBookings.length===1?'':'s'} assigned`:'No sessions assigned today'}</p></div><span className="engCount">{todayBookings.length}</span></div><div className="engSessionStack">{todayBookings.length?todayBookings.map(b=><Card key={b.id} b={b} today={today}/>):<div className="engEmpty"><div>✦</div><b>No sessions today.</b><p>Use the quick actions below for a walk-in or payment.</p></div>}</div></section>
 <section className="engSection"><div className="engSectionHead"><div><h2>Upcoming</h2><p>Next 14 days</p></div><span className="engCount subtle">{future.length}</span></div><div className="engSessionStack">{future.length?future.map(b=><Card key={b.id} b={b} today={today}/>):<div className="engEmpty"><b>No upcoming sessions assigned.</b><p>New assigned bookings will appear here automatically.</p></div>}</div></section>
 <section className="engSection"><h2>Quick actions</h2><div className="engQuickGrid"><Link href="/admin/artists?new=1" className="engQuick primary"><span>＋</span><div><b>New artist</b><small>Register a client</small></div></Link><Link href="/admin/payments" className="engQuick"><span>£</span><div><b>Take payment</b><small>Session or hours</small></div></Link><Link href="/admin/artists" className="engQuick"><span>⌕</span><div><b>Find artist</b><small>Profile & history</small></div></Link><Link href="/admin/sessions" className="engQuick"><span>✓</span><div><b>Log session</b><small>Complete report</small></div></Link></div></section>
 {recent.length>0&&<section className="engSection"><div className="engSectionHead"><div><h2>Recently completed</h2><p>Your last reports</p></div></div>{recent.map(r=><div className="engRecent" key={r.id}><div><b>{r.artist_name}</b><small>{r.session_date}</small></div><span>{r.actual_hours}h</span></div>)}</section>}<EngineerBottomNav/></main>
}
