import Link from 'next/link';
import {requireStaff} from '../../../lib/auth';
import {getAdminDb} from '../../../lib/supabase';
import {EngineerHeader,EngineerBottomNav} from '../../../components/EngineerShell';
import {formatUkDate} from '../../../lib/dates';
import {formatGBP} from '../../../lib/services';
export const dynamic='force-dynamic';
function addDays(dateStr,days){const d=new Date(dateStr+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function niceDay(dateStr,today){if(dateStr===today)return 'TODAY';if(dateStr===addDays(today,1))return 'TOMORROW';return new Date(dateStr+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'}).toUpperCase()}
function Card({b,today}){const dry=b.service_slug==='dry-hire';return <article className={`engSessionCard future ${dry?'dryHireSession':''}`}><div className="engSessionMeta"><span className="statusDot"></span><small>{niceDay(b.booking_date,today)}</small><b>{String(b.start_time).slice(0,5)}</b><small>{b.duration_minutes/60} hr</small></div><div className="engSessionMain"><h3>{b.customers?.artist_name||b.customers?.full_name}</h3><p>{b.service_name}</p><div className="engSessionBadges"><span className={b.payment_status==='paid'?'paid':'due'}>{b.payment_status==='paid'?'Paid':'Payment due'}</span>{dry&&<span className="dryHireBadge">Dry hire · no engineer</span>}</div><Link href={`/admin/engineer/session/${b.id}`} className="engPrimaryAction">View session <span>→</span></Link></div></article>}
export default async function EngineerHome(){
 const ctx=await requireStaff(); const db=getAdminDb(); const today=new Date().toISOString().slice(0,10),until=addDays(today,14);
 let q=db.from('bookings').select('*,customers(id,full_name,artist_name,email,phone)').gte('booking_date',today).lte('booking_date',until).in('status',['pending','confirmed']).order('booking_date').order('start_time');
 if(ctx.profile.role==='engineer')q=q.eq('engineer_user_id',ctx.user.id);
 const [{data:bookings=[]},{data:recent=[]}]=await Promise.all([q,db.from('session_reports').select('id,booking_id,customer_id,artist_name,session_date,actual_hours,work_completed,customers(phone,email)').eq('submitted_by_user_id',ctx.user.id).order('created_at',{ascending:false}).limit(3)]);
 let revenue=null;
 if(ctx.profile.role==='owner'){
  const month=today.slice(0,7)+'-01',monthDate=new Date(`${month}T00:00:00Z`),nextMonth=new Date(Date.UTC(monthDate.getUTCFullYear(),monthDate.getUTCMonth()+1,1)).toISOString().slice(0,10),prevMonth=new Date(Date.UTC(monthDate.getUTCFullYear(),monthDate.getUTCMonth()-1,1)).toISOString().slice(0,10);
  const [{data:mb=[]},{data:pb=[]},{data:mp=[]},{data:pp=[]}]=await Promise.all([
   db.from('bookings').select('amount_pence,refunded_amount_pence,payment_status,payment_method,created_at').in('payment_status',['paid','part_refunded','refunded']).neq('payment_method','credits').gte('created_at',month+'T00:00:00Z').lt('created_at',nextMonth+'T00:00:00Z'),
   db.from('bookings').select('amount_pence,refunded_amount_pence,payment_status,payment_method,created_at').in('payment_status',['paid','part_refunded','refunded']).neq('payment_method','credits').gte('created_at',prevMonth+'T00:00:00Z').lt('created_at',month+'T00:00:00Z'),
   db.from('studio_payments').select('amount_pence,refunded_amount_pence,status,paid_at').in('status',['paid','part_refunded','refunded']).gte('paid_at',month+'T00:00:00Z').lt('paid_at',nextMonth+'T00:00:00Z'),
   db.from('studio_payments').select('amount_pence,refunded_amount_pence,status,paid_at').in('status',['paid','part_refunded','refunded']).gte('paid_at',prevMonth+'T00:00:00Z').lt('paid_at',month+'T00:00:00Z')
  ]);
  const net=x=>Math.max(0,Number(x.amount_pence||0)-Number(x.refunded_amount_pence||0)),current=[...mb,...mp].reduce((n,x)=>n+net(x),0),previous=[...pb,...pp].reduce((n,x)=>n+net(x),0),change=previous?((current-previous)/previous)*100:null;
  const upcomingValue=bookings.filter(b=>b.booking_date>=today&&!['cancelled','completed'].includes(b.status)).reduce((n,b)=>n+Number(b.amount_pence||0),0);
  const outstanding=bookings.filter(b=>b.booking_date>=today&&!['cancelled','completed'].includes(b.status)&&!['paid','part_refunded','refunded'].includes(b.payment_status)&&b.payment_method!=='credits').reduce((n,b)=>n+Number(b.amount_pence||0),0);
  revenue={current,previous,change,upcomingValue,outstanding};
 }
 const todayBookings=bookings.filter(b=>b.booking_date===today),future=bookings.filter(b=>b.booking_date>today),first=(ctx.profile.full_name||'').split(' ')[0];
 return <main className="engApp"><EngineerHeader profile={ctx.profile}/><section className="engWelcome"><p className="eyebrow">Engineer dashboard</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, {first}.</h1><p>Your sessions, artists and payments — nothing else.</p></section>
 <section className="engSection"><div className="engSectionHead"><div><h2>Today</h2><p>{todayBookings.length?`${todayBookings.length} session${todayBookings.length===1?'':'s'} assigned`:'No sessions assigned today'}</p></div><span className="engCount">{todayBookings.length}</span></div><div className="engSessionStack">{todayBookings.length?todayBookings.map(b=><Card key={b.id} b={b} today={today}/>):<div className="engEmpty"><div>✦</div><b>No sessions today.</b><p>Use the quick actions below for a walk-in or payment.</p></div>}</div></section>
 <section className="engSection"><div className="engSectionHead"><div><h2>Upcoming</h2><p>Next 14 days</p></div><span className="engCount subtle">{future.length}</span></div><div className="engSessionStack">{future.length?future.map(b=><Card key={b.id} b={b} today={today}/>):<div className="engEmpty"><b>No upcoming sessions assigned.</b><p>New assigned bookings will appear here automatically.</p></div>}</div></section>
 <section className="engSection"><h2>Quick actions</h2><div className="engQuickGrid"><Link href="/admin/bookings/new" className="engQuick primary"><span>＋</span><div><b>New booking</b><small>DM / phone booking</small></div></Link><Link href="/admin/artists?new=1" className="engQuick"><span>＋</span><div><b>New artist</b><small>Register a client</small></div></Link><Link href="/admin/payments" className="engQuick"><span>£</span><div><b>Take payment</b><small>Session or hours</small></div></Link><Link href="/admin/artists" className="engQuick"><span>⌕</span><div><b>Find artist</b><small>Profile & history</small></div></Link><Link href="/admin/calendar" className="engQuick"><span>▦</span><div><b>Calendar</b><small>Visual studio schedule</small></div></Link><Link href="/admin/sessions" className="engQuick"><span>✓</span><div><b>Log past session</b><small>Cash / walk-in / catch-up</small></div></Link></div></section>
 {recent.length>0&&<section className="engSection"><div className="engSectionHead"><div><h2>Recently completed</h2><p>Tap a session to contact the customer or reopen it.</p></div></div><div className="recentCompletedList">{recent.map(r=>{const phone=String(r.customers?.phone||'').replace(/\s+/g,'');return <details className="engRecent expandable" key={r.id}><summary><div><b>{r.artist_name}</b><small>{formatUkDate(r.session_date)}</small></div><span>{r.actual_hours}h <em>⌄</em></span></summary><div className="recentCompletedBody">{r.work_completed&&<p>{r.work_completed}</p>}<div className="recentCompletedActions">{phone&&<><a href={`tel:${phone}`}>Call</a><a href={`sms:${phone}`}>Text</a></>}{r.booking_id&&<Link href={`/admin/engineer/session/${r.booking_id}`}>View session →</Link>}</div>{r.customers?.phone&&<small>{r.customers.phone}</small>}</div></details>})}</div></section>} {revenue&&<section className="engSection ownerRevenueHome compactRevenue"><div className="compactRevenueTop"><div><p className="eyebrow">Revenue · this month</p><b className="compactRevenueAmount">{formatGBP(revenue.current)}</b><span className={revenue.change===null?'muted':revenue.change>=0?'paidText':'dueText'}>{revenue.change===null?'No last-month baseline':`${revenue.change>=0?'↑':'↓'} ${Math.abs(revenue.change).toFixed(0)}% vs last month`}</span></div><Link href="/admin/accounting" className="textLink">Accounting →</Link></div><div className="compactRevenueStats"><span><small>Last month</small><b>{formatGBP(revenue.previous)}</b></span><span><small>Upcoming</small><b>{formatGBP(revenue.upcomingValue)}</b></span><span><small>To collect</small><b>{formatGBP(revenue.outstanding)}</b></span></div></section>}<EngineerBottomNav profile={ctx.profile}/></main>
}
