import LegalPage,{Section} from '../../components/LegalPage';
export const metadata={title:'Dry Hire Terms — Silkcrayon Studios'};
export default function DryHireTerms(){return <LegalPage eyebrow="Dry Hire · Version 2026-09-05" title="Studio Dry Hire Terms" intro="These additional terms apply whenever a booking is made as Studio Dry Hire. They sit alongside Silkcrayon’s general Terms, Cancellation Policy and No Harmful Music Policy.">
 <Section title="What dry hire includes"><p>Dry hire provides use of the booked Silkcrayon studio space and the installed equipment made available for that booking. It does not include a Silkcrayon recording engineer, producer, assistant, editing, mixing, mastering or Studio Finish unless separately agreed and paid for.</p></Section>
 <Section title="Competence & operation"><p>The booking customer must ensure that they or their own engineer can operate the session safely and competently. Silkcrayon is not responsible for lost recording time caused by unfamiliarity with software, personal equipment, session files, adapters or the customer’s own workflow.</p></Section>
 <Section title="Access & supervision"><p>Dry hire does not guarantee unattended access to the premises. Silkcrayon staff may remain on-site, manage entry and exit, and intervene where necessary to protect people, equipment or the premises.</p></Section>
 <Section title="Booked time & overtime"><p>Your booking starts and ends at the confirmed times. Setup, loading sessions, exporting, backing up and packing down must happen within that period. Additional time is subject to availability and is chargeable at the applicable dry-hire rate.</p></Section>
 <Section title="Equipment"><p>Studio equipment must remain in the studio and be used for its intended purpose. Do not rewire, dismantle, move fixed equipment or change system settings in a way that could affect later sessions without Silkcrayon approval. Any fault or damage must be reported immediately.</p></Section>
 <Section title="Damage & responsibility"><p>The booking customer is responsible for the conduct of their engineer and guests. Silkcrayon may charge the reasonable cost of repairing or replacing equipment or property damaged through deliberate, reckless or negligent behaviour.</p></Section>
 <Section title="Personal equipment & files"><p>Bring any laptops, drives, adapters, plugins, licences, session files or specialist accessories your workflow requires. Customers remain responsible for backing up their own recordings and files. Silkcrayon is not a permanent file-storage service.</p></Section>
 <Section title="Guests & conduct"><p>Guest limits and all general studio conduct rules continue to apply. Smoking, vaping, cannabis and illegal drugs are not permitted. The No Harmful Music Policy also applies to dry-hire sessions.</p></Section>
 <Section title="Cancellations"><p>Silkcrayon’s standard Cancellation & Refund Policy applies to dry hire unless a different arrangement is confirmed in writing.</p></Section>
 <Section title="Safety & right to stop a hire"><p>Silkcrayon may stop a dry-hire session where continued use creates a safety, legal, equipment or operational risk. Where the issue is caused by the customer or their guests, unused time may not be refundable.</p></Section>
 </LegalPage>}
