import Link from 'next/link';
import SiteHeader from '../../components/SiteHeader';

export const metadata={
 title:'Recording Studio Dry Hire Cardiff — £40/hr | Silkcrayon Studios',
 description:'Dry hire a professional recording studio in Cardiff Bay from £40/hour. Bring your own engineer or run your own session. 2-hour minimum.',
 alternates:{canonical:'/dry-hire-cardiff'}
};

export default function DryHireCardiff(){
 return <main className="marketingSite dryHirePage"><SiteHeader/>
  <section className="dryHireHero"><div className="container"><p className="eyebrow">Recording studio dry hire · Cardiff Bay</p><h1>Your session.<br/>Your engineer.<br/><span>Our studio.</span></h1><p className="lede">Use the Silkcrayon recording space without a Silkcrayon engineer. Built for producers, engineers and experienced artists who already know how they want to work.</p><div className="dryHirePrice"><b>£40</b><span>/ hour<br/><small>2-hour minimum · £80</small></span></div><div className="actions"><Link className="button primary" href="/booking?service=dry-hire">Book dry hire →</Link><Link className="button outline" href="/dry-hire-terms">Read the terms</Link></div></div></section>
  <section className="section"><div className="container dryHireIntro"><div><p className="eyebrow">Engineer-free studio hire</p><h2>Take the room.<br/>Run the session your way.</h2></div><p>Dry hire is for people who do not need Silkcrayon engineering. Bring your own engineer, producer or operate the session yourself. You get the studio environment, booth and installed equipment while keeping control of your workflow.</p><p><b>Lead hirer must be 18+.</b> If you are not already verified, Silkcrayon will send a secure photo-ID check after booking. The ID image is deleted after verification.</p></div></section>
  <section className="section dryHireIncluded"><div className="container"><p className="eyebrow">What is included</p><div className="dryHireFeatureGrid"><article><span>01</span><h3>Recording room & booth</h3><p>Private studio time in our Cardiff Bay space, including the dedicated vocal booth.</p></article><article><span>02</span><h3>Installed studio setup</h3><p>Use the studio monitoring and agreed installed recording equipment as part of the hire.</p></article><article><span>03</span><h3>Your own workflow</h3><p>Bring your own engineer, producer, laptop, drives and sessions. No Silkcrayon engineer is included.</p></article><article><span>04</span><h3>Studio access</h3><p>Silkcrayon manages access to the premises and may remain on-site while you work.</p></article></div></div></section>
  <section className="section"><div className="container dryHireWho"><div><p className="eyebrow">Best for</p><h2>You already know what you need.</h2></div><div><p>Independent engineers bringing an artist.</p><p>Producers who need a treated recording space.</p><p>Artists experienced enough to run their own recording session.</p><p>Podcasters and spoken-word creators with their own operator.</p></div></div></section>
  <section className="section dryHireRules"><div className="container"><p className="eyebrow">Before you book</p><h2>Dry hire means responsibility comes with the room.</h2><div className="dryHireRuleGrid"><p><b>No engineer included.</b> Silkcrayon will not operate your recording session unless separately agreed and paid for.</p><p><b>Booked time includes setup and pack-down.</b> Overtime is chargeable and depends on availability.</p><p><b>You are responsible for guests and equipment.</b> Negligent or deliberate damage may be charged to the booking customer.</p><p><b>Bring what your workflow needs.</b> Session files, drives, adapters, laptops and specialist accessories are your responsibility.</p></div><Link className="textLink" href="/dry-hire-terms">Read full Dry Hire Terms →</Link></div></section>
  <section className="section finalCta"><div className="container"><p className="eyebrow">Studio dry hire Cardiff</p><h2>Book the room.</h2><p>From £40/hour with a 2-hour minimum.</p><Link className="button primary large" href="/booking?service=dry-hire">Book dry hire <span>↗</span></Link></div></section>
 </main>
}
